project:
  type: website
  output-dir: docs

website:
  title: "Homework Portfolio"
  back-to-top-navigation: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: Homework/HW1/Homework_1.qmd
        text: Homework 1
      - href: Homework/HW2/Homework_2.qmd
        text: Homework 2
      - href: Homework/HW3/Homework_3.qmd
        text: Homework 3
      - href: Homework/HW4/Homework_4.qmd
        text: Homework 4
      - href: Homework/HW5/Homework_5.qmd
        text: Homework 5
      - href: Homework/HW6/Homework_6.qmd
        text: Homework 6
      - href: Homework/HW7/Homework_7.qmd
        text: Homework 7
      - href: Homework/HW8/Homework_8.qmd
        text: Homework 8

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

