{
  "hash": "69f6e36dc48fc7fb689b3cd5d9480e95",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"**MATH 3190 Homework 3**\"\nsubtitle: |\n  Due February 12, 2026\\\n  Focus: Notes 5\\\n  Total Points: 90 + 10 (Self-Critique Comment and Uploading to GitHub) = 100\nformat:\n  html:\n    embed-resources: true # Keep this so the html file is easily shareable.\nurlcolor: blue\nexecute: # Will set these as the default for all code chunks\n  eval: true\n  echo: true\neditor_options: \n  chunk_output_type: console\n---\n\n\n\nNote that your homework should be completed in Quarto. You can just add your answers and code to this document in the appropriate part. The file should be rendered as an html document or pdf document (html is quicker to render and you will need an installation of LaTeX to render as a pdf). You will \"turn in\" this homework by uploading the files, the .qmd and output file, to your GitHub `Math_3190_Assignment` repository in the `Homework/Homework_3` directory. Make sure all supporting files (if there are any) are in this directory as well. You should use `git` and `Unix` commands in a terminal for this (i.e. don't manually upload files to GitHub). In addition, you will submit just your html or pdf file on Canvas to unlock the solutions.\n\nDon't forget to also put a [self-critique comment]{.underline} on Canvas indicating what you did correctly and incorrectly and include any questions you may have about the assignment after submitting the assignment and thoroughly looking through the solutions.\n\n# Problem 1 (11 points)\n\n### Part a (9 points)\n\nSuppose we are attempting to predict a person's ability to run a marathon in under 4 hours (coded as a 1) based on a number of factors: age, sex, BMI, and blood pressure. Below is the confusion matrix in this situation:\n\n|                  | **Actual: 1** | **Actual: 0** |\n|:-----------------|:-------------:|:-------------:|\n| **Predicted: 1** |      58       |      102      |\n| **Predicted: 0** |      37       |      217      |\n\nFind each of the following. Use proper formatting in Quarto when you type your answers. You can put equations between dollar signs (`$$`) and you can use the `\\frac{}{}` (for a small fraction) or `\\dfrac{}{}` (for a larger one) commands to nicely type fractions.\n\n-   The prevalence of those that can run a mile under 4 hours.\n-   $\\frac{58}{414}$ or 0.14\n-   The overall accuracy of these predictions.\n-   0.66\n-   The sensitivity (recall).\n-   $\\frac{58}{95}$ or 0.51\n-   The specificity.\n-   $\\frac{217}{319}$ or 0.68\n-   The positive predictive value (precision).\n-   $\\frac{58}{160}$ or 0.36\n-   The negative predictive value.\n-   $\\frac{217}{254}$ 0.85\n-   The balanced accuracy.\n-   0.60\n-   Cohen's Kappa ($\\kappa$). Check out this link on [Wikipedia: Cohen's Kappa](https://en.wikipedia.org/wiki/Cohen%27s_kappa) and scroll down to the section entitled **Binary classification confusion matrix**.\n-   $$\\dfrac{2*(58*217-102*37)}{(58+102)*(217+102)+(58+37)*(37+217)}$$ 0.23\n-   F1 score. Check out what this is on [Wikipedia: F-Score](https://en.wikipedia.org/wiki/F-score)\n-   0.42\n\n### Part b (2 points)\n\nRead more of the Wikipedia article on Cohen's Kappa, especially the **Interpreting magnitude** and the **Limitations** part. I cannot really verify that you did this, so this is on your honor.\n\n# Problem 2 (79 points)\n\nThe `adult` dataset (from the UC Irvine [database](https://archive.ics.uci.edu/dataset/2/adult)) is one that is used to predict whether a person makes over \\$50K a year based on some other variables. The data came from the Census Bureau in 1994 and can be found in the Data folder in my Math3190_S26 GitHub repo. More info on the dataset can be found in the \"adult.names\" file.\n\n### Part a (4 points)\n\nRead the data into **R** as a tibble, change the column names to be descriptive about what the variable in that column is, and change the one containing salary information to a factor. Read the \"adult.names\" file to see the column names. Note that even though this file has a `.data.` suffix, it is comma separated, so you can read it in using `read.csv()` in base **R** and the convert it to a tibble or `read_csv()` from the tidyverse, which wil read it in as a tibble.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary('caret')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'caret' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: lattice\n\nAttaching package: 'caret'\n\nThe following object is masked from 'package:purrr':\n\n    lift\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nadult = read_csv(\"adult.data\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 32560 Columns: 15\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (9): State-gov, Bachelors, Never-married, Adm-clerical, Not-in-family, W...\ndbl (6): 39, 77516, 13, 2174, 0, 40\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nadult  = rename(adult, \"age\"=\"39\", 'workclass'='State-gov', 'finalweight'='77516', 'education'='Bachelors', 'edu_years'='13', 'marital_status'='Never-married', 'occupation'='Adm-clerical', 'relationship'='Not-in-family', 'race'='White', 'sex'='Male', 'capital_gain'='2174', 'capital_loss'='0', 'hrs_per_wk'='40', 'native_country'='United-States', 'target'='<=50K')\n\nadult = mutate(adult, target=as.factor(target))\n```\n:::\n\n\n\n### Part b (4 points)\n\nRandomly split the dataset into a training and a testing group. Let's use 4/5 of it for training and 1/5 for testing. You can do this with any function you'd like. Please set a seed with the `set.seed()` function before you do this so the results are reproducible.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny = adult$target\nset.seed(7)\ntest_index = createDataPartition(y, times = 1, p = 0.2, list=FALSE)\ntest = adult[test_index,]\ntrain = adult[-test_index,]\n```\n:::\n\n\n\n### Part c (5 points)\n\nFit two models for predicting whether a person's salary is above \\$50K or not:\n\nFor the first model, fit a logistic regression model using something like `glm(salary ~ age + education + race + sex + hours_per_week, data = adult_train, family = \"binomial\")`. By the way, if you are unfamiliar with logistic regression, take some time to research it online or in my notes from Math 3150, which you can find [here](https://drive.google.com/file/d/1qQajPxb9tdgx5Qal-ppsK18XEdzsXe1o/view?usp=sharing). We will deal with logistic regression again on the next homework. You don't need to know everything about it, just learn a little about how it is used to predict the class for an observation. Of course, I'm happy to explain how it works in office hours as well.\n\nFor the second model, fit a $k$ nearest neighbors model with $k=7$ neighbors using the `knn3()` function in the `caret` package. Again, use `age`, `education`, `race`, `sex`, and `hours_per_week` as the predictors.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_fit = glm(target ~ age + education + race + sex + hrs_per_wk, data = train, family = \"binomial\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_fit = knn3(target ~ age+education+race+sex+hrs_per_wk, data=train, k=7)\n```\n:::\n\n\n\n### Part d (5 points)\n\nWith logistic regression, the most common cutoff value for the predicted probability for predicting a \"success\" is 0.5. Using 0.5 as this cutoff (above 0.5 should be labeled as \"\\>50K\"), obtain the class predictions and convert the variable to a factor. You can use the `predict()` function with `type = \"response\"` to obtain the predicted probabilities of being in the \"\\>50K\" group and then compare those probabilities to 0.5. Then use the `confusionMatrix()` function in the `caret` package to obtain the confusion matrix and many associated statistics. Print all of the output from that function. Remember to use the `positive` argument in that function. The positive should be the `>50K` category.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny_hat_logit = predict(log_fit, train, type=\"response\")\npredicted <- ifelse(y_hat_logit >= 0.5, \">50K\", \"<=50K\")\n\nconfusionMatrix(as.factor(predicted), train$target, positive='>50K') # y hat needs to be a factor.\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction <=50K  >50K\n     <=50K 18502  3846\n     >50K   1273  2426\n                                          \n               Accuracy : 0.8035          \n                 95% CI : (0.7986, 0.8083)\n    No Information Rate : 0.7592          \n    P-Value [Acc > NIR] : < 2.2e-16       \n                                          \n                  Kappa : 0.3749          \n                                          \n Mcnemar's Test P-Value : < 2.2e-16       \n                                          \n            Sensitivity : 0.38680         \n            Specificity : 0.93563         \n         Pos Pred Value : 0.65585         \n         Neg Pred Value : 0.82790         \n             Prevalence : 0.24080         \n         Detection Rate : 0.09314         \n   Detection Prevalence : 0.14201         \n      Balanced Accuracy : 0.66121         \n                                          \n       'Positive' Class : >50K            \n                                          \n```\n\n\n:::\n:::\n\n\n\n### Part e (4 points)\n\nObtain the class predictions for your kNN model and output the results of the `confusionMatrix()` function for this. Note that it will take a few seconds to obtain the predictions for the kNN model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny_hat_knn = predict(knn_fit, train, type = 'class')\nconfusionMatrix(y_hat_knn, train$target, positive = \">50K\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction <=50K  >50K\n     <=50K 18262  3341\n     >50K   1513  2931\n                                          \n               Accuracy : 0.8136          \n                 95% CI : (0.8089, 0.8184)\n    No Information Rate : 0.7592          \n    P-Value [Acc > NIR] : < 2.2e-16       \n                                          \n                  Kappa : 0.434           \n                                          \n Mcnemar's Test P-Value : < 2.2e-16       \n                                          \n            Sensitivity : 0.4673          \n            Specificity : 0.9235          \n         Pos Pred Value : 0.6595          \n         Neg Pred Value : 0.8453          \n             Prevalence : 0.2408          \n         Detection Rate : 0.1125          \n   Detection Prevalence : 0.1706          \n      Balanced Accuracy : 0.6954          \n                                          \n       'Positive' Class : >50K            \n                                          \n```\n\n\n:::\n:::\n\n\n\n### Part f (4 points)\n\nUsing the output from parts d and e, write a few sentences comparing and contrasting the strengths and weaknesses of each model when it comes to predictions.\n\nkNN: Has a high specificity (0.92) and low sensitivity (0.46). It has a low false positives but high false negative. It's more prone to identifying people who DO make more than \\$50K as people who make less than/equal to 50K.\n\nlogistic regression: Also has high specificty (0.94) and low sensitivity (0.39).\n\n### Part g (8 points)\n\nUsing the `train()` function in the `caret` package, perform 5-fold cross validation for $k$ in the kNN model using only the training set and again using `age`, `education`, `race`, `sex`, and `hours_per_week` as the predictors. Set the search for $k$ to be from 1 to 21 (we'll stop at 21 to save time) in the `tuneGrid` argument. Make sure to use the `trControl` option to set it to cross validation. Then use Cohen's $\\kappa$ as the metric to determine the best $k$ value. You can change the metric in the `train()` function to Cohen's $\\kappa$ by putting in `metric = \"Kappa\"`.\n\nThen, if the best $k$ is different than 7, fit another kNN model with the optimal $k$ value. **Please set a seed at the beginning of this code chunk**.\n\nIt is fairly computationally expensive to optimize the $k$ for the kNN model here since it takes so long to obtain the predictions. So, this may take a few minutes to run. Note that you can add `#| cache: true` to the top of the code chunk to cache the output of the code so the code doesn't need to run each time you render the document.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\ntrain_knn = train(target~ age+education+race+sex+hrs_per_wk, method=\"knn\",\n                  data = train,\n                  trControl = trainControl(method='cv', number = 5),\n                  tuneGrid = data.frame(k = seq(1,21,2)),\n                  metric = \"Kappa\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_knn$bestTune\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  k\n3 5\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_fit2 = knn3(target ~ age+education+race+sex+hrs_per_wk, data=train, k=5)\n```\n:::\n\n\n\n### Part h (20 points)\n\nWe mentioned the most common cutoff value for the predicted probability for predicting a \"success\" in logistic regression is 0.5. However, we can adjust this value to make it easier or more difficult to predict a success. Let's optimize this cutoff value using 5-fold cross validation. Note: we could also do this with kNN, but we will not on this assignment.\n\nUsing the cutoff values from 0.15 to 0.85 by 0.05 (0.15, 0.20, 0.25, and so on up to 0.85) for predicting whether an adult has a salary above 50K, find which one performs best on the training set using the metric of Cohen's $\\kappa$, which is given in the output of the `confusionMatrix()` function. You will need a couple loops here since the `train()` function cannot do this for us. Note: you can find the indices of the rows in each fold using the `createFolds()` function in the `caret` library. Please set a seed at the beginning of your code chunk for this part.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\n\nfolds <- createFolds(train$target, k = 5)\n\ncutoffs <- seq(0.15, 0.85, by = 0.05)\n\nkappa_results <- numeric(length(cutoffs))\n\nfor (c in seq_along(cutoffs)) {\n  \n  cutoff <- cutoffs[c]\n  kappa_fold <- numeric(length(folds))\n  \n  for (i in seq_along(folds)) {\n    \n    test_idx <- folds[[i]]\n    train_data <- train[-test_idx, ]\n    test_data  <- train[test_idx, ]\n    \n    model <- glm(target ~ age+education+race+sex+hrs_per_wk, data = train_data, family = binomial)\n    \n    probs <- predict(model, newdata = test_data, type = \"response\")\n    \n    preds <- ifelse(probs > cutoff, \">50K\", \"<=50K\")\n    preds <- factor(preds, levels = levels(train$target))\n    \n    cm <- confusionMatrix(preds, test_data$target)\n    kappa_fold[i] <- cm$overall[\"Kappa\"]\n  }\n  \n  kappa_results[c] <- mean(kappa_fold)\n}\n\nresults <- data.frame(\n  cutoff = cutoffs,\n  mean_kappa = kappa_results\n)\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   cutoff mean_kappa\n1    0.15 0.31575594\n2    0.20 0.37481852\n3    0.25 0.41034916\n4    0.30 0.42588348\n5    0.35 0.43257183\n6    0.40 0.42170968\n7    0.45 0.40230448\n8    0.50 0.37276930\n9    0.55 0.33139679\n10   0.60 0.28769627\n11   0.65 0.24338265\n12   0.70 0.18741627\n13   0.75 0.13269608\n14   0.80 0.08152749\n15   0.85 0.04217737\n```\n\n\n:::\n\n```{.r .cell-code}\nbest_cutoff <- results$cutoff[which.max(results$mean_kappa)]\nbest_cutoff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.35\n```\n\n\n:::\n:::\n\n\n\n### Part i (5 points)\n\nOnce you have your \"optimal\" cutoff value, repeat part d using this cutoff and compare the results of this output to the results of the output for a kNN model with the optimal $k$ value you found in part g. For which statistics is the logistic regression better now and for which is it worse?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny_hat_logit = predict(log_fit, train, type=\"response\")\n\npredicted_classes <- ifelse(y_hat_logit >= 0.35, \">50K\", \"<=50K\")\nconfusionMatrix(as.factor(predicted_classes), train$target, positive = \">50K\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction <=50K  >50K\n     <=50K 16812  2550\n     >50K   2963  3722\n                                          \n               Accuracy : 0.7883          \n                 95% CI : (0.7833, 0.7933)\n    No Information Rate : 0.7592          \n    P-Value [Acc > NIR] : < 2.2e-16       \n                                          \n                  Kappa : 0.4338          \n                                          \n Mcnemar's Test P-Value : 2.875e-08       \n                                          \n            Sensitivity : 0.5934          \n            Specificity : 0.8502          \n         Pos Pred Value : 0.5568          \n         Neg Pred Value : 0.8683          \n             Prevalence : 0.2408          \n         Detection Rate : 0.1429          \n   Detection Prevalence : 0.2567          \n      Balanced Accuracy : 0.7218          \n                                          \n       'Positive' Class : >50K            \n                                          \n```\n\n\n:::\n:::\n\n\n\n### Part j (15 points)\n\nFinally, let's test our two models (the logistic model with the \"optimal\" cutoff and the kNN model with the \"optimal\" $k$) on the test set. We must keep a few things in mind:\n\n1.  We must use the exact models we fit to the training set. We aren't fitting new models here, we are just getting predictions from the test set using these models we already fit. You fit the logistic regression model in part c (with the best cutoff probability determined in part h) and you fit the kNN model in either part c or part g.\n2.  We should not use the results of the testing predictions to change our models. That should have been done with the training sets.\n\nFind the predictions for the test set using both models, print the output of the `confusionMatrix()` function for each model, and compare the results in a few sentences.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_result = predict(knn_fit2, test, type=\"class\")\nconfusionMatrix(knn_result, test$target, positive = \">50K\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction <=50K >50K\n     <=50K  4397  914\n     >50K    547  655\n                                          \n               Accuracy : 0.7757          \n                 95% CI : (0.7653, 0.7858)\n    No Information Rate : 0.7591          \n    P-Value [Acc > NIR] : 0.0008519       \n                                          \n                  Kappa : 0.3334          \n                                          \n Mcnemar's Test P-Value : < 2.2e-16       \n                                          \n            Sensitivity : 0.4175          \n            Specificity : 0.8894          \n         Pos Pred Value : 0.5449          \n         Neg Pred Value : 0.8279          \n             Prevalence : 0.2409          \n         Detection Rate : 0.1006          \n   Detection Prevalence : 0.1846          \n      Balanced Accuracy : 0.6534          \n                                          \n       'Positive' Class : >50K            \n                                          \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ny_hat_logit2 = predict(log_fit, train, type=\"response\")\npredicted2 <- ifelse(y_hat_logit >= 0.35, \">50K\", \"<=50K\")\n\nconfusionMatrix(as.factor(predicted2), train$target, positive='>50K') \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction <=50K  >50K\n     <=50K 16812  2550\n     >50K   2963  3722\n                                          \n               Accuracy : 0.7883          \n                 95% CI : (0.7833, 0.7933)\n    No Information Rate : 0.7592          \n    P-Value [Acc > NIR] : < 2.2e-16       \n                                          \n                  Kappa : 0.4338          \n                                          \n Mcnemar's Test P-Value : 2.875e-08       \n                                          \n            Sensitivity : 0.5934          \n            Specificity : 0.8502          \n         Pos Pred Value : 0.5568          \n         Neg Pred Value : 0.8683          \n             Prevalence : 0.2408          \n         Detection Rate : 0.1429          \n   Detection Prevalence : 0.2567          \n      Balanced Accuracy : 0.7218          \n                                          \n       'Positive' Class : >50K            \n                                          \n```\n\n\n:::\n:::\n\n\n\nlogistic regression: It has a high specificty (0.85) and low sensitivity (0.59). It has a higher balanced accuracy (0.65)\n\nkNN: it has a higher specificity (0.89) than the logistic regression model, but has a lower sensitivity (0.42). It also has a lower balanced accuracy (0.65)\n\n### Part k (5 points)\n\nEven though one method may be better on a given dataset than another, that does not mean that method will always predict better. However, logistic regression has a few advantages over kNN regardless of predictive power. List at least three advantages logistic regression has over kNN.\n\nLogistic regression is more easily interpreted than kNN. Logistic regression also seem to be less computationally expensive.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}