{
  "hash": "f3edb8c3cff189f7dc31f4054a9599d0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"**MATH 3190 Homework 6**\"\nsubtitle: |\n  Due March 5, 2026\\\n  Focus: Notes 7 Part 2\\\n  Total Points: 90 + 10 (Self-Critique Comment and Uploading to GitHub) = 100\nformat: \n  html:\n    embed-resources: true # Keep this so the html file is easily shareable.\nurlcolor: blue\nexecute: # Will set these as the default for all code chunks\n  eval: true\n  echo: true\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\nNote that your homework should be completed in Quarto. You can just add your answers and code to this document in the appropriate part. The file should be rendered as an html document or pdf document (html is quicker to render and you will need an installation of LaTeX to render as a pdf). You will \"turn in\" this homework by uploading the files, the .qmd and output file, to your GitHub `Math_3190_Assignment` repository in the `Homework/Homework_6` directory. Make sure all supporting files (if there are any) are in this directory as well. You should use `git` and `Unix` commands in a terminal for this (i.e. don't manually upload files to GitHub). In addition, you will submit just your html or pdf file on Canvas to unlock the solutions.\n\nDon't forget to also put a [self-critique comment]{.underline} on Canvas indicating what you did correctly and incorrectly and include any questions you may have about the assignment after submitting the assignment and thoroughly looking through the solutions.\n\n# Problem 1 (28 points)\n\nAn automobile consulting company wants to understand the factors on which the pricing of cars depends. The dataset `car_price_prediction` in the `math3190package` (and also found in the GitHub data folder) has information on the sales of 4340 vehicles\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(math3190package)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: tidyverse\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.1.0     \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(glmnet)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'glmnet' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: Matrix\n\nAttaching package: 'Matrix'\n\nThe following objects are masked from 'package:tidyr':\n\n    expand, pack, unpack\n\nLoaded glmnet 4.1-10\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(glmnetUtils)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'glmnetUtils' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'glmnetUtils'\n\nThe following objects are masked from 'package:glmnet':\n\n    cv.glmnet, glmnet\n```\n\n\n:::\n:::\n\n\n\n\n### Part a (3 points)\n\nCreate new variables in the dataset by taking the natural log of selling price, year, and km_driven. This will help linearize the association between variables. Then fit a linear model for predicting the log of selling price using all other variables except \"name\", \"year\", \"selling_price\", and \"km_driven\" (the logged variables should be used instread of those last three). Also, there is only one vehicle with a fuel type of \"Electric\". Remove that vehicle from the dataset.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf = car_price_prediction\ndf = df |>\n  mutate(selling_price_l=log(selling_price),\n         year_l = log(year),\n         km_driven_l = log(km_driven))\n\ncar_mod = lm(selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, df)\n\nprint(which(df$fuel == \"Electric\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4146\n```\n\n\n:::\n\n```{.r .cell-code}\ndf <- df[-4146, ]\n\nsummary(car_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = selling_price_l ~ year_l + km_driven_l + fuel + \n    seller_type + transmission + owner, data = df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.81328 -0.30394  0.00052  0.28819  2.32756 \n\nCoefficients:\n                              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                 -1.686e+03  3.345e+01 -50.406  < 2e-16 ***\nyear_l                       2.234e+02  4.389e+00  50.896  < 2e-16 ***\nkm_driven_l                 -3.601e-02  1.010e-02  -3.566 0.000366 ***\nfuelDiesel                   5.842e-01  7.526e-02   7.763 1.03e-14 ***\nfuelElectric                 1.943e-01  4.775e-01   0.407 0.684097    \nfuelLPG                     -5.132e-02  1.233e-01  -0.416 0.677337    \nfuelPetrol                   6.553e-02  7.539e-02   0.869 0.384754    \nseller_typeIndividual       -1.555e-01  1.817e-02  -8.555  < 2e-16 ***\nseller_typeTrustmark Dealer  3.089e-01  4.910e-02   6.292 3.45e-10 ***\ntransmissionManual          -8.001e-01  2.432e-02 -32.897  < 2e-16 ***\nownerFourth & Above Owner   -1.418e-01  5.502e-02  -2.577 0.010003 *  \nownerSecond Owner           -4.521e-02  1.840e-02  -2.458 0.014024 *  \nownerTest Drive Car          7.418e-02  1.192e-01   0.622 0.533702    \nownerThird Owner            -1.156e-01  3.058e-02  -3.780 0.000159 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4705 on 4326 degrees of freedom\nMultiple R-squared:  0.6866,\tAdjusted R-squared:  0.6857 \nF-statistic: 729.1 on 13 and 4326 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n### Part b (5 points)\n\nNow fit some LASSO models for predicting log selling price using all but the \"name\" variable. Try the following values for the regularization parameter: $\\lambda=0,\\ 0.01,\\ 0.1,$ and $1$ and comment on how the coefficients of the model change.\n\nNote: when $\\lambda=0$, the LASSO coefficients should equal the OLS model coefficients. However, they will actually be a bit off here. That is because the `glmnet()` function has a `thresh` argument that sets a threshold for convergence. It is, by default, set to `1e-07`. To make the parameters match, you can change that to `thresh = 1e-14` instead. This is not necessary, though.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lasso = glmnet(\n  selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df, alpha = 1\n)\n\ncoef(fit_lasso, s=0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                      s=0\n(Intercept)                 -1.688202e+03\nyear_l                       2.236094e+02\nkm_driven_l                 -3.481482e-02\nfuelCNG                     -5.127992e-02\nfuelDiesel                   5.152708e-01\nfuelLPG                     -9.718891e-02\nfuelPetrol                   .           \nseller_typeDealer            .           \nseller_typeIndividual       -1.549975e-01\nseller_typeTrustmark Dealer  2.999007e-01\ntransmissionAutomatic        7.961328e-01\ntransmissionManual          -5.989193e-12\nownerFirst Owner             4.409896e-02\nownerFourth & Above Owner   -8.628628e-02\nownerSecond Owner            .           \nownerTest Drive Car          9.618843e-02\nownerThird Owner            -6.528794e-02\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(fit_lasso, s=0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                   s=0.01\n(Intercept)                 -1.695903e+03\nyear_l                       2.246139e+02\nkm_driven_l                 -2.840263e-02\nfuelCNG                      .           \nfuelDiesel                   4.977172e-01\nfuelLPG                     -1.681638e-03\nfuelPetrol                   .           \nseller_typeDealer            .           \nseller_typeIndividual       -1.520611e-01\nseller_typeTrustmark Dealer  2.550091e-01\ntransmissionAutomatic        7.764286e-01\ntransmissionManual          -4.087513e-12\nownerFirst Owner             3.877399e-02\nownerFourth & Above Owner   -3.446985e-02\nownerSecond Owner            .           \nownerTest Drive Car          .           \nownerThird Owner            -3.994509e-02\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(fit_lasso, s=0.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                    s=0.1\n(Intercept)                 -1.570380e+03\nyear_l                       2.080811e+02\nkm_driven_l                  .           \nfuelCNG                      .           \nfuelDiesel                   3.219320e-01\nfuelLPG                      .           \nfuelPetrol                   .           \nseller_typeDealer            .           \nseller_typeIndividual       -4.682138e-02\nseller_typeTrustmark Dealer  .           \ntransmissionAutomatic        5.659971e-01\ntransmissionManual          -7.989083e-13\nownerFirst Owner             .           \nownerFourth & Above Owner    .           \nownerSecond Owner            .           \nownerTest Drive Car          .           \nownerThird Owner             .           \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(fit_lasso, s=1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                 s=1\n(Intercept)                 12.76421\nyear_l                       .      \nkm_driven_l                  .      \nfuelCNG                      .      \nfuelDiesel                   .      \nfuelLPG                      .      \nfuelPetrol                   .      \nseller_typeDealer            .      \nseller_typeIndividual        .      \nseller_typeTrustmark Dealer  .      \ntransmissionAutomatic        .      \ntransmissionManual           .      \nownerFirst Owner             .      \nownerFourth & Above Owner    .      \nownerSecond Owner            .      \nownerTest Drive Car          .      \nownerThird Owner             .      \n```\n\n\n:::\n:::\n\n\n\n\nAs lambda increases, the coefficients move closer to zero, and more variables get eliminated. All variables are eliminated at lambda = 1\n\n### Part c (4 points)\n\nNow fit some ridge regression models for predicting log selling price using all but name. Try the following values for the regularization parameter: $\\lambda=0,\\ 0.01,\\ 0.1,$ and $1$ and comment on how the coefficients of the model change.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ridge = glmnet(\n  selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df, alpha = 0\n)\n\ncoef(fit_ridge, s=0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                      s=0\n(Intercept)                 -1.535519e+03\nyear_l                       2.036382e+02\nkm_driven_l                 -5.028479e-02\nfuelCNG                     -2.874915e-01\nfuelDiesel                   2.680145e-01\nfuelLPG                     -3.593852e-01\nfuelPetrol                  -2.496458e-01\nseller_typeDealer            5.756947e-02\nseller_typeIndividual       -9.723745e-02\nseller_typeTrustmark Dealer  3.555044e-01\ntransmissionAutomatic        3.931004e-01\ntransmissionManual          -3.908969e-01\nownerFirst Owner             5.101052e-02\nownerFourth & Above Owner   -1.415577e-01\nownerSecond Owner           -2.025005e-02\nownerTest Drive Car          1.183101e-01\nownerThird Owner            -9.765032e-02\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(fit_ridge, s=0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                   s=0.01\n(Intercept)                 -1.535519e+03\nyear_l                       2.036382e+02\nkm_driven_l                 -5.028479e-02\nfuelCNG                     -2.874915e-01\nfuelDiesel                   2.680145e-01\nfuelLPG                     -3.593852e-01\nfuelPetrol                  -2.496458e-01\nseller_typeDealer            5.756947e-02\nseller_typeIndividual       -9.723745e-02\nseller_typeTrustmark Dealer  3.555044e-01\ntransmissionAutomatic        3.931004e-01\ntransmissionManual          -3.908969e-01\nownerFirst Owner             5.101052e-02\nownerFourth & Above Owner   -1.415577e-01\nownerSecond Owner           -2.025005e-02\nownerTest Drive Car          1.183101e-01\nownerThird Owner            -9.765032e-02\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(fit_ridge, s=0.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                    s=0.1\n(Intercept)                 -1.448383e+03\nyear_l                       1.921926e+02\nkm_driven_l                 -5.702026e-02\nfuelCNG                     -2.712297e-01\nfuelDiesel                   2.660287e-01\nfuelLPG                     -3.536293e-01\nfuelPetrol                  -2.481538e-01\nseller_typeDealer            5.809819e-02\nseller_typeIndividual       -9.683171e-02\nseller_typeTrustmark Dealer  3.479386e-01\ntransmissionAutomatic        3.871974e-01\ntransmissionManual          -3.853069e-01\nownerFirst Owner             6.029604e-02\nownerFourth & Above Owner   -1.592260e-01\nownerSecond Owner           -2.570233e-02\nownerTest Drive Car          1.265398e-01\nownerThird Owner            -1.063213e-01\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(fit_ridge, s=1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                      s=1\n(Intercept)                 -730.31692858\nyear_l                        97.80312738\nkm_driven_l                   -0.06636058\nfuelCNG                       -0.13708925\nfuelDiesel                     0.19295626\nfuelLPG                       -0.24602649\nfuelPetrol                    -0.18278935\nseller_typeDealer              0.06707861\nseller_typeIndividual         -0.09121385\nseller_typeTrustmark Dealer    0.23393485\ntransmissionAutomatic          0.28582962\ntransmissionManual            -0.28578180\nownerFirst Owner               0.10341686\nownerFourth & Above Owner     -0.20942432\nownerSecond Owner             -0.06163726\nownerTest Drive Car            0.18323925\nownerThird Owner              -0.13229443\n```\n\n\n:::\n:::\n\n\n\n\nThe coefficients become further from 0 as the lambda value increases. No variables are eliminated\n\n### Part d (4 points)\n\nNow fit some elastic net regression models for predicting log price using all but name. Try the following values for the regularization parameter: $\\lambda=0,\\ 0.01,\\ 0.1,$ and $1$ for $\\alpha=1/3$ and then comment on how the coefficients of the model change for each $\\alpha$ from parts (b), (c), and (d).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_elastic = glmnet(\n  selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df, alpha = 1/3\n)\n\ncoef(fit_elastic, s=0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                      s=0\n(Intercept)                 -1.679553e+03\nyear_l                       2.225388e+02\nkm_driven_l                 -3.577061e-02\nfuelCNG                     -1.569495e-01\nfuelDiesel                   4.113615e-01\nfuelLPG                     -2.050619e-01\nfuelPetrol                  -1.040946e-01\nseller_typeDealer            .           \nseller_typeIndividual       -1.547799e-01\nseller_typeTrustmark Dealer  3.012906e-01\ntransmissionAutomatic        4.053108e-01\ntransmissionManual          -3.908553e-01\nownerFirst Owner             4.564855e-02\nownerFourth & Above Owner   -8.960239e-02\nownerSecond Owner            .           \nownerTest Drive Car          1.013616e-01\nownerThird Owner            -6.670104e-02\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(fit_elastic, s=0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                   s=0.01\n(Intercept)                 -1.670372e+03\nyear_l                       2.213313e+02\nkm_driven_l                 -3.542321e-02\nfuelCNG                     -1.383028e-01\nfuelDiesel                   4.076942e-01\nfuelLPG                     -1.818925e-01\nfuelPetrol                  -1.032087e-01\nseller_typeDealer            .           \nseller_typeIndividual       -1.537674e-01\nseller_typeTrustmark Dealer  2.906093e-01\ntransmissionAutomatic        4.017905e-01\ntransmissionManual          -3.888549e-01\nownerFirst Owner             4.623111e-02\nownerFourth & Above Owner   -7.981953e-02\nownerSecond Owner            .           \nownerTest Drive Car          7.606237e-02\nownerThird Owner            -6.153545e-02\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(fit_elastic, s=0.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                    s=0.1\n(Intercept)                 -1.534857e+03\nyear_l                       2.034996e+02\nkm_driven_l                 -2.280243e-02\nfuelCNG                      .           \nfuelDiesel                   3.181901e-01\nfuelLPG                      .           \nfuelPetrol                  -1.214408e-01\nseller_typeDealer            .           \nseller_typeIndividual       -1.317799e-01\nseller_typeTrustmark Dealer  1.422951e-01\ntransmissionAutomatic        3.585269e-01\ntransmissionManual          -3.512336e-01\nownerFirst Owner             5.247914e-02\nownerFourth & Above Owner    .           \nownerSecond Owner            .           \nownerTest Drive Car          .           \nownerThird Owner             .           \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(fit_elastic, s=1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                      s=1\n(Intercept)                 -4.944253e+02\nyear_l                       6.667039e+01\nkm_driven_l                  .           \nfuelCNG                      .           \nfuelDiesel                   .           \nfuelLPG                      .           \nfuelPetrol                   .           \nseller_typeDealer            .           \nseller_typeIndividual        .           \nseller_typeTrustmark Dealer  .           \ntransmissionAutomatic        6.790119e-04\ntransmissionManual          -6.763769e-04\nownerFirst Owner             .           \nownerFourth & Above Owner    .           \nownerSecond Owner            .           \nownerTest Drive Car          .           \nownerThird Owner             .           \n```\n\n\n:::\n:::\n\n\n\n\n### Part e (4 points)\n\nUse the `cv.glmnet()` to find the \"optimal\" $\\lambda$ value (let's use the \"lambda.1se\") for LASSO ($\\alpha=1$), ridge ($\\alpha=0$), and elastic net (let's again use $\\alpha = 1/3$) and then fit models using the `glmnet()` function for all three using their respective \"best\" $\\lambda$. **Set a seed** before running the `cv.glmnet()` each time.\n\nCompare each model's variables and coefficients.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LASSO\nset.seed(7)\ncvfit_lasso = cv.glmnet(\n  selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df, alpha = 1\n)\n\ncvfit_lasso$lambda.1se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03264975\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_lasso = glmnet(\n  selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df, alpha = 1, lambda = cvfit_lasso$lambda.1se\n  )\n\ncoef(fit_lasso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                       s0\n(Intercept)                 -1.709506e+03\nyear_l                       2.263710e+02\nkm_driven_l                 -3.447434e-03\nfuelCNG                      .           \nfuelDiesel                   4.417323e-01\nfuelLPG                      .           \nfuelPetrol                   .           \nseller_typeDealer            .           \nseller_typeIndividual       -1.380249e-01\nseller_typeTrustmark Dealer  1.377066e-01\ntransmissionAutomatic        7.247498e-01\ntransmissionManual          -2.998143e-13\nownerFirst Owner             2.058869e-02\nownerFourth & Above Owner    .           \nownerSecond Owner            .           \nownerTest Drive Car          .           \nownerThird Owner             .           \n```\n\n\n:::\n\n```{.r .cell-code}\n# Elastic net\n\nset.seed(7)\ncvfit_elastic = cv.glmnet(\n  selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df, alpha = 1/3\n)\n\ncvfit_lasso$lambda.1se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03264975\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_elastic = glmnet(\n  selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df, alpha = 1, lambda = cvfit_elastic$lambda.1se)\n\ncoef(fit_elastic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                       s0\n(Intercept)                 -1.633439e+03\nyear_l                       2.163707e+02\nkm_driven_l                  .           \nfuelCNG                      .           \nfuelDiesel                   3.664337e-01\nfuelLPG                      .           \nfuelPetrol                   .           \nseller_typeDealer            .           \nseller_typeIndividual       -8.860718e-02\nseller_typeTrustmark Dealer  .           \ntransmissionAutomatic        6.266209e-01\ntransmissionManual          -1.300025e-13\nownerFirst Owner             .           \nownerFourth & Above Owner    .           \nownerSecond Owner            .           \nownerTest Drive Car          .           \nownerThird Owner             .           \n```\n\n\n:::\n\n```{.r .cell-code}\n# Ridge\nset.seed(7)\ncvfit_ridge = cv.glmnet(\n  selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df, alpha = 0\n  )\n\ncvfit_ridge$lambda.1se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1624986\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_ridge = glmnet(\n  selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df, alpha = 0, lambda = cvfit_ridge$lambda.1se\n  )\n\ncoef(fit_ridge)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n17 x 1 sparse Matrix of class \"dgCMatrix\"\n                                       s0\n(Intercept)                 -1.339015e+03\nyear_l                       1.778242e+02\nkm_driven_l                 -6.380799e-02\nfuelCNG                     -2.504270e-01\nfuelDiesel                   2.620901e-01\nfuelLPG                     -3.443425e-01\nfuelPetrol                  -2.444557e-01\nseller_typeDealer            5.931243e-02\nseller_typeIndividual       -9.623728e-02\nseller_typeTrustmark Dealer  3.369956e-01\ntransmissionAutomatic        3.787531e-01\ntransmissionManual          -3.766769e-01\nownerFirst Owner             7.222753e-02\nownerFourth & Above Owner   -1.780510e-01\nownerSecond Owner           -3.177652e-02\nownerTest Drive Car          1.394003e-01\nownerThird Owner            -1.154443e-01\n```\n\n\n:::\n:::\n\n\n\n\nThe coefficients for LASSO and elastic model is similar in value. Elastic model has fewer variables. The ridge model has all variables.\n\n### Part f (8 points)\n\nUse bootstrapping with at least 1000 samples to estimate the standard errors of the coefficients of the ridge regression model. For each bootstrap sample, run the `cv.glmnet()` function to find the best $\\lambda$ and fit a model using that optimized $\\lambda$. Use the \"lambda.1se\" for this. This can take a few minutes to run. Then compare these bootstrapped standard errors to the standard errors for the OLS model you fit in part a. Are they larger or smaller? Does this make sense?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootcases = function(resids, i) {\n  cvfit = cv.glmnet(selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df[i,], alpha = 0)\n  fit = glmnet(selling_price_l~year_l+km_driven_l+fuel+seller_type+transmission+owner, data= df[i,], alpha=0, lambda = cvfit$lambda.1se)\n  coef(fit)[,1]\n}\n\nboot_out = bootstrapping(residuals(car_mod), bootcases, 1000)\nboot_out\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 17 × 5\n   term                        sample_average original_value      bias std.error\n   <chr>                                <dbl>          <dbl>     <dbl>     <dbl>\n 1 (Intercept)                     -1353.         -1362.       8.98e+0  45.9    \n 2 year_l                            180.           181.      -1.18e+0   6.02   \n 3 km_driven_l                        -0.0632        -0.0625  -6.78e-4   0.00919\n 4 fuelCNG                            -0.254         -0.255    6.27e-4   0.0419 \n 5 fuelDiesel                          0.263          0.263   -8.01e-6   0.00738\n 6 fuelLPG                            -0.345         -0.346    1.54e-3   0.0485 \n 7 fuelPetrol                         -0.245         -0.245   -1.42e-4   0.00732\n 8 seller_typeDealer                   0.0590         0.0591  -4.88e-5   0.00849\n 9 seller_typeIndividual              -0.0963        -0.0963  -1.12e-5   0.00786\n10 seller_typeTrustmark Dealer         0.340          0.340    2.32e-5   0.0289 \n11 transmissionAutomatic               0.380          0.381   -6.52e-4   0.0154 \n12 transmissionManual                 -0.378         -0.378    6.20e-4   0.0152 \n13 ownerFirst Owner                    0.0710         0.0701   8.74e-4   0.00912\n14 ownerFourth & Above Owner          -0.174         -0.174    1.36e-5   0.0469 \n15 ownerSecond Owner                  -0.0308        -0.0302  -5.79e-4   0.0103 \n16 ownerTest Drive Car                 0.136          0.137   -1.27e-3   0.0639 \n17 ownerThird Owner                   -0.115         -0.113   -1.76e-3   0.0237 \n```\n\n\n:::\n:::\n\n\n\n\nBootstrapped standard errors are smaller than the standard errors in the OLS model. This makes sense bcause ridge regression reduces variance.\n\n# Problem 2 (21 points)\n\nIn 1990, sixty districts in California were randomly selected with the goal of predicting the median house value for the district based on the district location (longitude and latitude), the median house age in the block group, the total number of rooms in the homes, the total number of bedrooms, the population in the district, the number of households, and the median income (in \\$10,000). The data are already in the .qmd file.\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n### Part a (2 points)\n\nUsing the training set, fit a linear regression model predicting house value from the other variables.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlin_mod = lm(house_value ~ ., data = housing_train)\n```\n:::\n\n\n\n\n### Part b (4 points)\n\nFit a ridge regression using `cv.glmnet()` to choose the optimal $\\lambda$ using \"lambda.min\". Set the seed before using`cv.glmnet()`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\ncvfit_ridge2 = cv.glmnet(house_value~., data=housing_train, alpha=0)\nfit_ridge = glmnet(\n  house_value~., data = housing_train, alpha=0, lambda= cvfit_ridge2$lambda.min\n)\n```\n:::\n\n\n\n\n### Part c (5 points)\n\nCompute the sum of squared errors (that is $\\sum_{i=1}^n (y_i-\\hat{y}_i)^2$ for both the OLS model and the ridge regression model for the **training set**. The `predict()` functions will be useful here. Compare the results and comment on why the OLS performs better here (the OLS should indeed perform better).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# \nsse_ols_train <- sum((housing_train$house_value - predict(lin_mod))^2)\nsse_ols_train\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.2027e+11\n```\n\n\n:::\n\n```{.r .cell-code}\nyhat_ridge_train <- predict(fit_ridge, housing_train)\nsse_ridge_train <- sum((housing_train$house_value - yhat_ridge_train)^2) + \n  cvfit_ridge2$lambda.min*sum(fit_ridge$beta^2)\nsse_ridge_train\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.388492e+13\n```\n\n\n:::\n:::\n\n\n\n\nThe OLS model does perform better because we are using the training set. OLS has high variance but low bias while ridge regression has the opposite. Therefore, OLS can overfit and performs better on the training set.\n\n### Part d (3 points)\n\nCompute the sum of squared errors (that is $\\sum_{i=1}^n (y_i-\\hat{y}_i)^2$ for both the OLS model and the ridge regression model for the **testing set**. Remember to use the exact models you fit to the training sets. The `predict()` functions will be useful here. Compare the results and comment on why the ridge regression performs better here.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: 2d\n\nsse_ols_test <- sum((housing_test$house_value - predict(lin_mod))^2)\nsse_ols_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 695193665334\n```\n\n\n:::\n\n```{.r .cell-code}\nyhat_ridge_test <- predict(fit_ridge, housing_test)\nsse_ridge_test <- sum((housing_test$house_value - yhat_ridge_test)^2) + \n  cvfit_ridge2$lambda.min*sum(fit_ridge$beta^2)\nsse_ridge_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.372685e+13\n```\n\n\n:::\n:::\n\n\n\n\nRidge regression does better than OLS for the testing set because OLS can overfit while ridge regression doesn't. Ridge regression is better generalized and can stabilize when presented with noisy data.\n\n### Part e (7 points)\n\nUse the `train()` function in the `caret()` package to find the optimal $\\alpha, \\lambda$ pair in this situation (using the training set and **10-fold cross validation**). For $\\lambda$, search for values between 0 and 10000 by 100 and for $\\alpha$, search for values between 0 and 1 by 0.05. Then fit a model using the optimal $\\alpha$ and $\\lambda$ using `glmnet()` and compare the sum of squared errors using this optimized model on the test set to the two models in part (d). Set a seed before running the `train()` function.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(caret)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'caret' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: lattice\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'caret'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:purrr':\n\n    lift\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(7)\n\nop_mod = train(house_value~., method=\"glmnet\", \n               data = housing_train,\n               tuneGrid = expand.grid(alpha = seq(0, 1, 0.05), \n                                      lambda = seq(0, 10000, 100)),\n               trControl = trainControl(method = \"cv\", number = 10))\nggplot(op_mod, highlight=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `aes_string()` was deprecated in ggplot2 3.0.0.\nℹ Please use tidy evaluation idioms with `aes()`.\nℹ See also `vignette(\"ggplot2-in-packages\")` for more information.\nℹ The deprecated feature was likely used in the caret package.\n  Please report the issue at <https://github.com/topepo/caret/issues>.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The shape palette can deal with a maximum of 6 discrete values because more\nthan 6 becomes difficult to discriminate\nℹ you have requested 21 values. Consider specifying shapes manually if you need\n  that many of them.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1515 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Homework_6_files/figure-html/2e-1.png){width=672}\n:::\n\n```{.r .cell-code}\nop_mod$bestTune\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   alpha lambda\n36     0   3500\n```\n\n\n:::\n\n```{.r .cell-code}\n#fit model\nbest_mod = glmnet(house_value~., data = housing_train, alpha=0.05, lambda=3500)\n\n# find sse\nyhat_best <- predict(best_mod, housing_test)\nsse_best <- sum((housing_test$house_value - yhat_best)^2) + \n  3500*(0.05*sum(best_mod$beta^2))\nsse_best\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 682984098629\n```\n\n\n:::\n:::\n\n\n\n\n# Problem 3 (41 points)\n\nIn the `AER` package is the data set \"ShipAccidents\". You can install that package and load that data using `data(ShipAccidents)`. Type `?ShipAccidents` to read about that data set.\n\n### Part a (4 points)\n\nLoad in the data, remove the rows for which service is equal to 0, and then fit a Poisson regression model for predicting incidents from all other variables using the ShipAccidents data. Don't forget to put `family = \"poisson\"` in the `glm()` function. Briefly explain why it makes sense to do Poisson regression here.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(AER)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'AER' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: car\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'car' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'carData' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'car'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:purrr':\n\n    some\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: lmtest\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lmtest' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: zoo\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'zoo' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'zoo'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    as.Date, as.Date.numeric\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: sandwich\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'sandwich' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: survival\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'survival'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:caret':\n\n    cluster\n```\n\n\n:::\n\n```{.r .cell-code}\ndata(ShipAccidents)\nship = ShipAccidents\n\nship <- ship |>\n  filter(service != 0)\n\npos_mod=glm(incidents~., data=ship, family=\"poisson\")\n```\n:::\n\n\n\n\nThe response variable is a count-based variable\n\n### Part b (5 points)\n\nUsing that model, interpret the slope of \"service\" and the slope of \"construction1970-74\" in original (not log) units.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pos_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = incidents ~ ., family = \"poisson\", data = ship)\n\nCoefficients:\n                      Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          2.657e-01  2.776e-01   0.957 0.338454    \ntypeB                7.030e-01  2.187e-01   3.214 0.001308 ** \ntypeC               -1.196e+00  3.275e-01  -3.653 0.000259 ***\ntypeD               -8.320e-01  2.877e-01  -2.892 0.003831 ** \ntypeE               -2.492e-01  2.360e-01  -1.056 0.291027    \nconstruction1965-69  1.048e+00  1.798e-01   5.832 5.47e-09 ***\nconstruction1970-74  1.446e+00  2.264e-01   6.387 1.70e-10 ***\nconstruction1975-79  6.788e-01  2.774e-01   2.447 0.014399 *  \noperation1975-79     7.031e-01  1.358e-01   5.178 2.24e-07 ***\nservice              6.421e-05  8.593e-06   7.473 7.86e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 614.54  on 33  degrees of freedom\nResidual deviance:  77.45  on 24  degrees of freedom\nAIC: 195.32\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n\nAs the aggregate months of service on the ship increases by 1 month, the average number of incidents is predicted to change by a factor of exp(0.06)\n\n### Part c (6 points)\n\nMake a residual plot of the Pearson residuals vs the linear predictors and make a QQ plot of the Pearson residuals. Comment on what these imply about the fit.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_resids = residuals(pos_mod, type=\"pearson\")\nresid_df = data.frame(p_resids,\n                      linear_pred = pos_mod$linear.predictors)\nggplot(resid_df, aes(x=linear_pred, y=p_resids)) +\n  geom_point(size=2) +\n  labs(x = \"Linear Predictors\", y = 'Pearson Residuals') +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Homework_6_files/figure-html/3c-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(resid_df, aes(sample=p_resids)) +\n  geom_qq()+\n  geom_qq_line(linewidth=1) +\n  labs(x='Theoretical Quantiles',\n       y='Sample Quantiles') +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Homework_6_files/figure-html/3c-2.png){width=672}\n:::\n:::\n\n\n\n\nThe QQ plot shows that the residuals are not normally distributed, which means the model may not be a good fit. The residual plot looks pretty good.\n\n### Part d (5 points)\n\nConduct a deviance goodness-of-fit (GOF) test for a lack of fit here. Type out the null and alternative hypotheses, report the test statistic, give the p-value, and provide an interpretation.\n\nH0 = The model is correctly specified\n\nHA = The model is incorrectly specified\n\nResidual deviance = 77.45\n\np-value = 0.00000015\n\nWe have strong evidence that the model is incorrectly specified.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pchisq(pos_mod$deviance, df = pos_mod$df.residual)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.542447e-07\n```\n\n\n:::\n:::\n\n\n\n\n### Part e (4 points)\n\nIs there evidence that this model has overdispersion? Explain.\n\nYes, one of the predictors are not significant.\n\n### Part f (6 points)\n\nFit a \"quasipoisson\" model to these data. Using this model, obtain an approximate 95% confidence interval for the mean response for a ship of type \"B\" with construction between 1965 and 1969, with operation between 1960 and 1974, and with 2000 aggregate months of service. You can construct this interval using a t critical value with 24 degrees of freedom since the quasipoisson family more closely follows a t distribution than a normal one. Interpret the interval.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquasi_mod = glm(formula = incidents ~., family = \"quasipoisson\", data=ship)\n\nsummary(quasi_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = incidents ~ ., family = \"quasipoisson\", data = ship)\n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          2.657e-01  4.724e-01   0.562 0.579020    \ntypeB                7.030e-01  3.722e-01   1.889 0.071078 .  \ntypeC               -1.196e+00  5.574e-01  -2.146 0.042167 *  \ntypeD               -8.320e-01  4.896e-01  -1.699 0.102218    \ntypeE               -2.492e-01  4.017e-01  -0.620 0.540827    \nconstruction1965-69  1.048e+00  3.059e-01   3.427 0.002206 ** \nconstruction1970-74  1.446e+00  3.854e-01   3.753 0.000982 ***\nconstruction1975-79  6.788e-01  4.721e-01   1.438 0.163364    \noperation1975-79     7.031e-01  2.311e-01   3.043 0.005604 ** \nservice              6.421e-05  1.462e-05   4.391 0.000196 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for quasipoisson family taken to be 2.896314)\n\n    Null deviance: 614.54  on 33  degrees of freedom\nResidual deviance:  77.45  on 24  degrees of freedom\nAIC: NA\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n\n```{.r .cell-code}\nship_pred = predict(quasi_mod, \n                    data.frame(type=\"B\",\n                               construction = \"1965-69\",\n                               operation = \"1960-74\",\n                               service = 2000),\n                    se.fit=T)\n\ntcrit = qt(0.975, df = 24)\ntcrit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.063899\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(ship_pred$fit - tcrit * ship_pred$se.fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n3.662335 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(ship_pred$fit + tcrit * ship_pred$se.fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n19.94579 \n```\n\n\n:::\n:::\n\n\n\n\nWe are 95% confident that the true average number of incidents for a ship of type \"B\" with construction between 1965 and 1969, with operation betwen 1960 and 1974, and with 2000 aggregate months of service is between 3.66 and 19.95.\n\n### Part g (5 points)\n\nNow construct an approximate 95% prediction interval for the number of incidents for the ship described in part f using the `qpois()` function. Interpret the interval.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqpois(0.05, 3.66)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nqpois(0.95, 19.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28\n```\n\n\n:::\n:::\n\n\n\n\nWe are 95% confident that the true number of incidents for a ship of type \"B\" with construction between 1965 and 1969, with operation betwen 1960 and 1974, and with 2000 aggregate months of service is between 1 and 28.\n\n### Part h (6 points)\n\nSuppose we did not catch the fact that this model is overdispersed. Repeat parts f and g using the model fit with the \"poisson\" family, not \"quasipoisson\" and using a z interval for the mean response rather than a t interval. Compare your results to parts f and g and comment on what is different.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nship_pred = predict(pos_mod, \n                    data.frame(type=\"B\",\n                               construction = \"1965-69\",\n                               operation = \"1960-74\",\n                               service = 2000),\n                    se.fit=T)\n\n\nexp(ship_pred$fit - 1.96 * ship_pred$se.fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n5.326349 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(ship_pred$fit + 1.96 * ship_pred$se.fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n13.71449 \n```\n\n\n:::\n:::\n\n\n\n\nWe are 95% confident that the true average number of incidents for a ship of type \"B\" with construction between 1965 and 1969, with operation betwen 1960 and 1974, and with 2000 aggregate months of service is between 5.33 and 13.71.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: 3h2\n\nqpois(0.05, 5.33)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\nqpois(0.95, 13.71)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20\n```\n\n\n:::\n:::\n\n\n\n\nWe are 95% confident that the true number of incidents for a ship of type \"B\" with construction between 1965 and 1969, with operation betwen 1960 and 1974, and with 2000 aggregate months of service is between 2 and 20.\n\nThe confidence/prediction interval for the normal Poisson model is smaller than that of the quasi-Poisson model.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}