{
  "hash": "980d2f88484545324a6904365a340f86",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"**MATH 3190 Homework 5**\"\nsubtitle: |\n  Due February 26, 2026\\\n  Focus: Boostrapping from Notes 5 and Notes 7 Part 1\\\n  Total Points: 90 + 10 (Self-Critique Comment and Uploading to GitHub) = 100\nformat: \n  html:\n    embed-resources: true # Keep this so the html file is easily shareable.\nurlcolor: blue\nexecute: # Will set these as the default for all code chunks\n  eval: true\n  echo: true\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\nNote that your homework should be completed in Quarto. You can just add your answers and code to this document in the appropriate part. The file should be rendered as an html document or pdf document (html is quicker to render and you will need an installation of LaTeX to render as a pdf). You will \"turn in\" this homework by uploading the files, the .qmd and output file, to your GitHub `Math_3190_Assignment` repository in the `Homework/Homework_5` directory. Make sure all supporting files (if there are any) are in this directory as well. You should use `git` and `Unix` commands in a terminal for this (i.e. don't manually upload files to GitHub). In addition, you will submit just your html or pdf file on Canvas to unlock the solutions.\n\nDon't forget to also put a [self-critique comment]{.underline} on Canvas indicating what you did correctly and incorrectly and include any questions you may have about the assignment after submitting the assignment and thoroughly looking through the solutions.\n\nAlso, there is a package I created with many functions and data files we will be using for the remainder of this class. You can install this package instead of downloading and reading in the data files. To download the package, do the following in **R**:\n\n1.  Install the remotes or the `devtools` package using either `install.packages(\"remotes\")` or `install.packages(\"devtools\")`.\n2.  Load the package: `library(remotes)` or `library(devtools)`.\n3.  Install the course package: `install_github(\"rbrown53/math3190package\")`. If it asks you if you want to update packages, you can select that you do.\n4.  Now, you will simply have to load the package (which will also load the `tidyverse`) for each homework assignment: `library(math3190package)`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(devtools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'devtools' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: usethis\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'usethis' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(caret)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'caret' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: lattice\n\nAttaching package: 'caret'\n\nThe following object is masked from 'package:purrr':\n\n    lift\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(math3190package)\n```\n:::\n\n\n\n\n# Problem 1 (35 points)\n\nWe first covered bootstrapping in Notes 5, but we returned to it here. Let's do a problem on bootstrapping that takes ideas from Notes 5 and Notes 7.\n\nThe amount of money spent on health care is an important issue for workers because many companies provide health insurance that only partial covers many medical procedures. The director of employee benefits at a midsize company wants to determine the amount spent on health care by the typical hourly worker in the company. A random sample of 25 workers is selected and the amounts they spent on their family’s health care needs during the past year can be found in the `healthcare` tibble in the `math3190package`.\n\n### Part a (4 points)\n\nGraph the data using both a boxplot and normal quantile plot (QQ plot) and use these to assess whether the population has a normal distribution.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(healthcare,aes(x=amount))+\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Homework_5_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(healthcare,aes(sample=amount))+\n  geom_qq_line() +\n  geom_qq()\n```\n\n::: {.cell-output-display}\n![](Homework_5_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\nThe distribution seems to be right tailed. There are many outliers\n\n### Part b (4 points)\n\nConstruct a 95% confidence interval for the mean cost per household using a t-interval. You can use the `t.test()` function for this. Interpret this confidence interval in context of the problem and comment on whether the t-procedure is appropriate to use here.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(healthcare$amount, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  healthcare$amount\nt = 2.8884, df = 24, p-value = 0.008078\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 163.5954 982.6446\nsample estimates:\nmean of x \n   573.12 \n```\n\n\n:::\n:::\n\n\n\n\nWe are 95% confident that the true mean of healthcare spending per family is between \\$163.60 and \\$982.64. It is not appropriate to use the t-procedure because the sample does not follow normal distribution.\n\n### Part c (7 points)\n\nNow let’s use bootstrapping to estimate a 95% interval for the mean.\n\nFirst, write a loop yourself that will do this. In the loop, you’ll need to sample from your data set with replacement, take the mean of that sample, and then store those means. Have the loop do this 10,000 times. Then you can obtain a 95% interval by using the quantile function in **R**. Specifically, you can type `quantile(means_vector, c(0.025, 0.975))` (if you call your vector `means_vector`) to get a 95% interval based on the percentile method.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\n\nmeans_vector = c()\nfor (i in 1:10000){\n  means_vector = c(means_vector, mean(slice_sample(healthcare, n=25,replace=T)$amount))\n}\nview(means_vector)\nquantile(unlist(means_vector), c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   2.5%   97.5% \n253.559 995.270 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 253.56 < mu < 995.27\n```\n:::\n\n\n\n\n253.56 \\< $\\mu$ \\< 995.27\n\n### Part d (5 points)\n\nNow use the `bootstrapping()` function in the `math3190package` library to obtain a bootstrap object using 10,000 samples. Then use the `boot_ci()` function to obtain the 95% intervals. Report the Percentile interval and BCa interval. Compare your interval from part (c) to the Percentile interval computed here. They should be similar.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\n\nmean_function = function(x,i) {\n  mean(x[i])\n}\n\nboothc = bootstrapping(healthcare$amount, mean_function,10000)\nboot_ci(boothc)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 10000 bootstrap replicates\n\n# A tibble: 4 × 4\n  interval_type conf_level lower upper\n  <chr>              <dbl> <dbl> <dbl>\n1 normal              0.95  196.  954.\n2 basic               0.95  144.  890.\n3 percent             0.95  256. 1002.\n4 bca                 0.95  303. 1208.\n\nCalculations and Intervals on Original Scale\nSome BCa intervals may be unstable\n```\n\n\n:::\n\n```{.r .cell-code}\n# 303 1208\n```\n:::\n\n\n\n\nPercentile: 256 \\< $\\mu$ \\< 1002\n\nBCA: 303 \\< $\\mu$ \\< 1208\n\n### Part e (3 points)\n\nWrite a sentence or two comparing the intervals you obtained in parts (c) and (d) to the t-interval you constructed in part (b).\n\nThe intervals are all very similar.\n\n### Part g (4 points)\n\nUse the `boostrapping()` function with at least 10,000 samples to obtain a 95% confidence interval based on BCa for the median.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\n\nmed_function = function(x,i) {\n  median(x[i])\n}\n\nboothcmed = bootstrapping(healthcare$amount, med_function,10000)\nboot_ci(boothcmed)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 10000 bootstrap replicates\n\n# A tibble: 4 × 4\n  interval_type conf_level lower upper\n  <chr>              <dbl> <dbl> <dbl>\n1 normal              0.95  146.  272.\n2 basic               0.95  108   242 \n3 percent             0.95  208   342 \n4 bca                 0.95  207   326 \n\nCalculations and Intervals on Original Scale\nSome BCa intervals may be unstable\n```\n\n\n:::\n\n```{.r .cell-code}\n# 207 < median < 326\n```\n:::\n\n\n\n\n### Part h (5 points)\n\nThe IQR is a measure of spread commonly used with the median. Construct a 95% confidence interval based on BCa for the IQR using the `bootstrapping()` function with at least 10,000 samples and interpret the interval. Also plot the output of the `bootstrapping()` function and comment on whether the distribution looks close to normal.S\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\n\niqr_function = function(x,i) {\n  IQR(x[i])\n}\n\nboothciqr = bootstrapping(healthcare$amount, iqr_function,10000)\nboot_ci(boothciqr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 10000 bootstrap replicates\n\n# A tibble: 4 × 4\n  interval_type conf_level lower upper\n  <chr>              <dbl> <dbl> <dbl>\n1 normal              0.95 -300.  488.\n2 basic               0.95  -83   229 \n3 percent             0.95   47   359 \n4 bca                 0.95   47   330 \n\nCalculations and Intervals on Original Scale\nSome BCa intervals may be unstable\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(boothciqr)\n```\n\n::: {.cell-output-display}\n![](Homework_5_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\nWe are 95% confident that the true IQR for the amount spent on healthcare per family is between 47 and 330. The bootstrapped values do not look normal at all; it's very skewed to the right.\n\n### Part i (3 points)\n\nIn all of these bootstraps, what did we have to assume about the population in order for these intervals to be valid?\n\nWe have to assume that the population is infinite/incredibly large.\n\n# Problem 2 (55 points)\n\nConcrete is the most important material in civil engineering. The concrete compressive strength is an important attribute of the concrete and our goal is to predict the concrete compressive strength (in MPa) from the following variables:\n\n-   Cement (in $\\text{kg}/\\text{m}^3$)\n-   Blast furnace slag (in $\\text{kg}/\\text{m}^3$)\n-   Fly ash (in $\\text{kg}/\\text{m}^3$)\n-   Water (in $\\text{kg}/\\text{m}^3$)\n-   Superplasticizer (in $\\text{kg}/\\text{m}^3$)\n-   Coarse aggregate (in $\\text{kg}/\\text{m}^3$)\n-   Fine aggregate (in $\\text{kg}/\\text{m}^3$)\n-   Age of concrete (in days)\n\nThis dataset came from the [UCI ML Repository](https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength) and can be found on the Math3190_Sp26 GitHub page along with a Readme file and in the `Concrete_Data` tibble in the `math3190package` **R** library.\n\n### Part a (2 points)\n\nChange the names of the variables in `Concrete_Data` so they are shorter yet still descriptive. Name this something other than `Concrete_Data` so you don't overwrite it.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\ndf = Concrete_Data\n\ndf = df |> \n     rename('cement' = 'Cement (component 1)(kg in a m^3 mixture)',\n            'fly_ash' = \"Fly Ash (component 3)(kg in a m^3 mixture)\",\n            'superplastic' = \"Superplasticizer (component 5)(kg in a m^3 mixture)\",\n            'fine_agg' = \"Fine Aggregate (component 7)(kg in a m^3 mixture)\",\n            'ccs' = \"Concrete compressive strength(MPa, megapascals)\",\n            'slag' = \"Blast Furnace Slag (component 2)(kg in a m^3 mixture)\",\n            'water' = \"Water  (component 4)(kg in a m^3 mixture)\",\n            'course_agg' = \"Coarse Aggregate  (component 6)(kg in a m^3 mixture)\",\n            'age' = \"Age (day)\" )\n\ndf <- na.omit(df)\n```\n:::\n\n\n\n\n### Part b (5 points)\n\nIn the `GGally` library is the function `ggpairs()`, which makes a nice scatterplot matrix in the `ggplot2` style. `GGally` should have already been installed when you installed `math3190package`, so you will just need to load it. Using `ggpairs()`, Create this scatterplot matrix for all of the variables in the dataset (they should all be plotted together in one plot).\n\nComment on the scatterplot matrix. Which variables seem to have a (at least somewhat) linear relationship with compressive strength?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GGally)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'GGally' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code}\nggpairs(df)\n```\n\n::: {.cell-output-display}\n![](Homework_5_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n\nCement has the highest linear relationship with compressive strength with a correlation coefficient of 0.498.\n\n### Part c (3 points)\n\nFit a linear model (with the `lm()` function) predicting compressive strength using all other variables. After you've done that, interpret the slope of the water variable in the context of the problem and answer whether it is considered a significant variable in the model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconc_mod = lm(ccs ~., df)\nsummary(conc_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ccs ~ ., data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-28.653  -6.303   0.704   6.562  34.446 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -23.163756  26.588421  -0.871 0.383851    \ncement         0.119785   0.008489  14.110  < 2e-16 ***\nslag           0.103847   0.010136  10.245  < 2e-16 ***\nfly_ash        0.087943   0.012585   6.988 5.03e-12 ***\nwater         -0.150298   0.040179  -3.741 0.000194 ***\nsuperplastic   0.290687   0.093460   3.110 0.001921 ** \ncourse_agg     0.018030   0.009394   1.919 0.055227 .  \nfine_agg       0.020154   0.010703   1.883 0.059968 .  \nage            0.114226   0.005427  21.046  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.4 on 1021 degrees of freedom\nMultiple R-squared:  0.6155,\tAdjusted R-squared:  0.6125 \nF-statistic: 204.3 on 8 and 1021 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nAs water increases by 1kg in a m\\^3 mixture, the concrete compressive strength decreases by 0.15 MPa, holding all other variables constant. It is significant with a p-value of 0.0002\n\n### Part d (6 points)\n\nUsing `ggplot()`, make a QQ plot of the raw residuals (obtained using the `residuals()` function). Include the QQ line as well. Comment on whether the residuals appear to be approximately normal.\n\nUsing `ggplot()`, make a plot of the jackknife residuals (obtained using the `rstudent()` function) on the y-axis and the fitted values of the model on the x-axis. Comment on whether this residual plot looks good. If it does not, indicate what the problem(s) is (are).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(resids=residuals(conc_mod))|>\n  ggplot(aes(sample=resids))+\n  geom_qq_line()+\n  geom_qq()+\n  labs(title=\"QQ plot\")\n```\n\n::: {.cell-output-display}\n![](Homework_5_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\nAccording to the raw residuals, the residuals seem normal. It seems slightly short tailed.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(resids=rstudent(conc_mod),\n           fitted = fitted.values(conc_mod)) |>\n  ggplot(aes(x=fitted, y=resids)) +\n  geom_point()+\n  geom_smooth(method='loess', formula = 'y~x', se=F)+\n  labs(x=\"fitted values\", y = \"jackknife residuals\")\n```\n\n::: {.cell-output-display}\n![](Homework_5_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\nThis doesn't look very good; it has a fanning shape.\n\n### Part e (6 points)\n\nSince the residual plots do not look good, let's try to use weighted least squares. Following the code on page 118 and 119 of Notes 7, create a vector of weights and then fit a new model using weighted least squares.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted = conc_mod$fitted.values\ne_mod = lm(abs(conc_mod$residuals)~fitted)\n\nw = 1/e_mod$fitted.values^2\nconc_mod_w = lm(ccs~., data = df, weights=w)\nsummary(conc_mod_w)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ccs ~ ., data = df, weights = w)\n\nWeighted Residuals:\n    Min      1Q  Median      3Q     Max \n-3.5154 -0.8319  0.0884  0.8213  4.5462 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -32.403699  24.543797  -1.320  0.18705    \ncement         0.123304   0.007963  15.484  < 2e-16 ***\nslag           0.102893   0.009346  11.010  < 2e-16 ***\nfly_ash        0.081794   0.011420   7.162 1.52e-12 ***\nwater         -0.110369   0.036820  -2.998  0.00279 ** \nsuperplastic   0.441258   0.092782   4.756 2.26e-06 ***\ncourse_agg     0.017182   0.008628   1.991  0.04669 *  \nfine_agg       0.020097   0.009886   2.033  0.04233 *  \nage            0.146670   0.006189  23.699  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.208 on 1021 degrees of freedom\nMultiple R-squared:  0.6547,\tAdjusted R-squared:  0.652 \nF-statistic:   242 on 8 and 1021 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n### Part f (5 points)\n\nUsing `ggplot()`, make a plot of the jackknife residuals (obtained using the `rstudent()` function) on the y-axis and the fitted values of the weighted model on the x-axis. Comment on whether this residual plot looks good and whether this plot looks better than the residual plot in part d.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(resids=rstudent(conc_mod_w),\n           fitted = fitted.values(conc_mod_w)) |>\n  ggplot(aes(x=fitted, y=resids)) +\n  geom_point()+\n  geom_smooth(method='loess', formula = 'y~x', se=F)+\n  labs(x=\"fitted values\", y = \"jackknife residuals\")\n```\n\n::: {.cell-output-display}\n![](Homework_5_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\nIt looks worse.\n\n### Part f (8 points)\n\nUsing the unweighted model from part c and the weighted model from part e, find and report both a confidence interval for the mean compressive strength and a prediction interval for the specific compressive strength for concrete that has a cement value of 300, a blast furnace slag of 90, a fly ash of 50, a water value of 200, a superplasticizer of 2.5, a coarse aggregate of 900, a fine aggregate of 600, and an age of 300 days. You can use the `predict()` function here and remember that you will need to find the specific weight for the given predictor variable values for the weighted intervals. You can follow along with the code used on page 121 of Notes 7.\n\nComment on how these intervals differ. Does the change make sense given the value of the fitted value?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# unweighted \n\n#confidence\npredict(conc_mod,data.frame(cement=300,slag=90, fly_ash=50,water=200,superplastic=2.5, course_agg = 900, fine_agg=600, age=300), interval=\"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 59.76989 55.66444 63.87534\n```\n\n\n:::\n\n```{.r .cell-code}\n# 55.66 63.88\n\n#prediction\npredict(conc_mod, data.frame(cement=300,slag=90, fly_ash=50,water=200,superplastic=2.5, course_agg = 900, fine_agg=600, age=300), interval=\"prediction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 59.76989 38.95351 80.58627\n```\n\n\n:::\n\n```{.r .cell-code}\n# 38.95 63.59\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#weighted\nnew_point = data.frame(cement=300, slag=90, fly_ash=50,water=200, superplastic=2.5, course_agg = 900, fine_agg=600, age=300)\n\n#confidence\npredict(conc_mod_w, data.frame(cement=300,slag=90, fly_ash=50,water=200,superplastic=2.5, course_agg = 900, fine_agg=600, age=300), interval=\"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 68.49046 64.15589 72.82503\n```\n\n\n:::\n\n```{.r .cell-code}\n# 64.16 72.83\n\n# prediction\nnew_fit = predict(conc_mod, new_point)\nnew_weight = 1/predict(e_mod, data.frame(fitted=new_fit))^2\npredict(conc_mod_w, new_point, interval=\"prediction\", weight = new_weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit     lwr      upr\n1 68.49046 39.9145 97.06641\n```\n\n\n:::\n\n```{.r .cell-code}\n# 39.91 97.10\n\npredict(conc_mod_w, new_point)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n68.49046 \n```\n\n\n:::\n\n```{.r .cell-code}\npredict(conc_mod, new_point)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n59.76989 \n```\n\n\n:::\n:::\n\n\n\n\nThe confidence and prediction intervals are larger when using WLS than OLS. This can be due to the fact that the residuals get bigger as the fitted values get bigger, which results in a wider interval band for WLS. The fitted value is relatively big, which results in the WLS interval band becoming bigger than OLS interval band.\n\n### Part g (10 points)\n\nWrite a function called `predict_weighted` that takes three inputs: the **unweighted** model, a data frame containing information about the value(s) of the predictor variables we are using to predict, and the interval type (either \"confidence\" or \"prediction\"). This function should return the predicted value and the interval bounds for the specified interval type for weighted least squares. So, this function should compute the weights, obtain the weighted least squares model, find the specific weight for the new value, and then get the prediction and the interval. This function should work for any linear model (made with the `lm()` function) you give it, not just for this exact situation of this problem. So, you should not reference any data sets or variables specific to this concrete problem in the function.\n\nTest this new function for the confidence and prediction intervals you made in part f.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict_weighted = function(uw_mod, predictor_vars, type){\n  fitted = uw_mod$fitted.values\n  e_mod = lm(abs(uw_mod$residuals)~fitted)\n  w = 1/e_mod$fitted.values^2\n  w_mod = lm(formula(uw_mod), data=model.frame(uw_mod), weights=w)\n  \n  new_fit = predict(uw_mod, predictor_vars)\n  new_weight = 1/predict(e_mod, data.frame(fitted=new_fit))^2\n  \n  if (type==\"confidence\") {\n    predict(w_mod, predictor_vars, interval=type)\n  } else {\n    predict(w_mod, predictor_vars, interval=type, weight=new_weight)\n  }\n}\n\npredict_weighted(conc_mod, new_point, \"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 68.49046 64.15589 72.82503\n```\n\n\n:::\n\n```{.r .cell-code}\npredict_weighted(conc_mod, new_point, \"prediction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit     lwr      upr\n1 68.49046 39.9145 97.06641\n```\n\n\n:::\n:::\n\n\n\n\n### Part h (5 points)\n\nIn this problem, based on the residual plots in part d, we found you the errors do not have constant variance. Another remedial measure for models with non-constant variance (heteroskedasticity) is to bootstrap the cases.\n\nUsing the `boostrapping()` function in `math3190package`, run a bootstrap of the cases for at least 5,000 bootstrap samples on the model coefficients. Note that an unweighted model should be fit when bootstrapping.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(math3190package)\nbootcases = function(resids, i){\n  lm(ccs ~ ., data = df[i,])$coef\n}\nboot = bootstrapping(residuals(conc_mod), bootcases, 5000)\nboot_ci(boot)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 5000 bootstrap replicates\n\nInfo for stat1\n# A tibble: 4 × 4\n  interval_type conf_level lower upper\n  <chr>              <dbl> <dbl> <dbl>\n1 normal              0.95 -80.2  34.1\n2 basic               0.95 -82.3  32.7\n3 percent             0.95 -79.0  35.9\n4 bca                 0.95 -78.8  36.4\n\nInfo for stat2\n# A tibble: 4 × 4\n  interval_type conf_level lower upper\n  <chr>              <dbl> <dbl> <dbl>\n1 normal              0.95 0.102 0.138\n2 basic               0.95 0.102 0.138\n3 percent             0.95 0.102 0.138\n4 bca                 0.95 0.102 0.138\n\nInfo for stat3\n# A tibble: 4 × 4\n  interval_type conf_level  lower upper\n  <chr>              <dbl>  <dbl> <dbl>\n1 normal              0.95 0.0819 0.126\n2 basic               0.95 0.0816 0.125\n3 percent             0.95 0.0824 0.126\n4 bca                 0.95 0.0824 0.126\n\nInfo for stat4\n# A tibble: 4 × 4\n  interval_type conf_level  lower upper\n  <chr>              <dbl>  <dbl> <dbl>\n1 normal              0.95 0.0626 0.113\n2 basic               0.95 0.0622 0.113\n3 percent             0.95 0.0629 0.114\n4 bca                 0.95 0.0627 0.114\n\nInfo for stat5\n# A tibble: 4 × 4\n  interval_type conf_level  lower   upper\n  <chr>              <dbl>  <dbl>   <dbl>\n1 normal              0.95 -0.239 -0.0611\n2 basic               0.95 -0.238 -0.0599\n3 percent             0.95 -0.241 -0.0628\n4 bca                 0.95 -0.240 -0.0625\n\nInfo for stat6\n# A tibble: 4 × 4\n  interval_type conf_level  lower upper\n  <chr>              <dbl>  <dbl> <dbl>\n1 normal              0.95 0.0824 0.497\n2 basic               0.95 0.0804 0.489\n3 percent             0.95 0.0923 0.501\n4 bca                 0.95 0.0951 0.504\n\nInfo for stat7\n# A tibble: 4 × 4\n  interval_type conf_level    lower  upper\n  <chr>              <dbl>    <dbl>  <dbl>\n1 normal              0.95 -0.00204 0.0380\n2 basic               0.95 -0.00160 0.0382\n3 percent             0.95 -0.00213 0.0377\n4 bca                 0.95 -0.00249 0.0374\n\nInfo for stat8\n# A tibble: 4 × 4\n  interval_type conf_level    lower  upper\n  <chr>              <dbl>    <dbl>  <dbl>\n1 normal              0.95 -0.00232 0.0425\n2 basic               0.95 -0.00197 0.0433\n3 percent             0.95 -0.00297 0.0423\n4 bca                 0.95 -0.00345 0.0415\n\nInfo for stat9\n# A tibble: 4 × 4\n  interval_type conf_level  lower upper\n  <chr>              <dbl>  <dbl> <dbl>\n1 normal              0.95 0.0966 0.130\n2 basic               0.95 0.0950 0.129\n3 percent             0.95 0.0995 0.133\n4 bca                 0.95 0.0984 0.132\n\nCalculations and Intervals on Original Scale\nSome BCa intervals may be unstable\n```\n\n\n:::\n:::\n\n\n\n\n### Part i (5 points)\n\nCompare the means and standard deviations for the bootstrapped coefficients along with the estimate and standard errors for the coefficients for both the weighted and unweighted models. Write a few sentences comparing them. If done correctly, the standard errors when bootstrapping should be larger. Why is that the case?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(boot)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 5\n  term         sample_average original_value       bias std.error\n  <chr>                 <dbl>          <dbl>      <dbl>     <dbl>\n1 (Intercept)        -23.3          -23.2    -0.0941     29.1    \n2 cement               0.120          0.120   0.0000186   0.00912\n3 slag                 0.104          0.104   0.0000583   0.0112 \n4 fly_ash              0.0880         0.0879  0.0000509   0.0129 \n5 water               -0.151         -0.150  -0.000312    0.0453 \n6 superplastic         0.292          0.291   0.00110     0.106  \n7 course_agg           0.0181         0.0180  0.0000438   0.0102 \n8 fine_agg             0.0202         0.0202  0.0000820   0.0114 \n9 age                  0.115          0.114   0.000762    0.00862\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(conc_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ccs ~ ., data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-28.653  -6.303   0.704   6.562  34.446 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -23.163756  26.588421  -0.871 0.383851    \ncement         0.119785   0.008489  14.110  < 2e-16 ***\nslag           0.103847   0.010136  10.245  < 2e-16 ***\nfly_ash        0.087943   0.012585   6.988 5.03e-12 ***\nwater         -0.150298   0.040179  -3.741 0.000194 ***\nsuperplastic   0.290687   0.093460   3.110 0.001921 ** \ncourse_agg     0.018030   0.009394   1.919 0.055227 .  \nfine_agg       0.020154   0.010703   1.883 0.059968 .  \nage            0.114226   0.005427  21.046  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.4 on 1021 degrees of freedom\nMultiple R-squared:  0.6155,\tAdjusted R-squared:  0.6125 \nF-statistic: 204.3 on 8 and 1021 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(conc_mod_w)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ccs ~ ., data = df, weights = w)\n\nWeighted Residuals:\n    Min      1Q  Median      3Q     Max \n-3.5154 -0.8319  0.0884  0.8213  4.5462 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -32.403699  24.543797  -1.320  0.18705    \ncement         0.123304   0.007963  15.484  < 2e-16 ***\nslag           0.102893   0.009346  11.010  < 2e-16 ***\nfly_ash        0.081794   0.011420   7.162 1.52e-12 ***\nwater         -0.110369   0.036820  -2.998  0.00279 ** \nsuperplastic   0.441258   0.092782   4.756 2.26e-06 ***\ncourse_agg     0.017182   0.008628   1.991  0.04669 *  \nfine_agg       0.020097   0.009886   2.033  0.04233 *  \nage            0.146670   0.006189  23.699  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.208 on 1021 degrees of freedom\nMultiple R-squared:  0.6547,\tAdjusted R-squared:  0.652 \nF-statistic:   242 on 8 and 1021 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nAll the coefficients are similar between bootstrapped, weighted, and unweighted. The standard error for bootstrapping is larger than the models. This is because fewer assumptions need to be met for bootstrapping.\n",
    "supporting": [
      "Homework_5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}