{
  "hash": "a282e13c99211b12e198db5d3fe153bc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"**MATH 3190 Homework 8**\"\nsubtitle: |\n  Due April 2, 2026\\\n  Focus: Notes 9\\\n  Total Points: 90 + 10 (Self-Critique Comment and Uploading to GitHub) = 100\nformat: \n  html:\n    embed-resources: true # Keep this so the html file is easily shareable.\nurlcolor: blue\nexecute: # Will set these as the default for all code chunks\n  eval: true\n  echo: true\neditor_options: \n  chunk_output_type: console\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n\nNote that your homework should be completed in Quarto. You can just add\nyour answers and code to this document in the appropriate part. The file\nshould be rendered as an html document or pdf document (html is quicker\nto render and you will need an installation of LaTeX to render as a\npdf). You will \"turn in\" this homework by uploading the files, the .qmd\nand output file, to your GitHub `Math_3190_Assignment` repository in the\n`Homework/Homework_8` directory. Make sure all supporting files (if\nthere are any) are in this directory as well. You should use `git` and\n`Unix` commands in a terminal for this (i.e. don't manually upload files\nto GitHub). In addition, you will submit just your html or pdf file on\nCanvas to unlock the solutions.\n\nDon't forget to also put a [self-critique comment]{.underline} on Canvas\nindicating what you did correctly and incorrectly and include any\nquestions you may have about the assignment after submitting the\nassignment and thoroughly looking through the solutions.\n\n# Problem 1 (10 points)\n\nThree airlines serve a small town in Ohio. Airline A has 52% of all\nscheduled flights, airline B has 35% and airline C has the remaining\n13%. Their on-time rates are 85%, 67%, and 41%, respectively. A flight\njust left on-time. What is the probability that it was a flight of\nairline A?\n\n60.56%\n\n# Problem 2 (15 points)\n\nSuppose we have a data set with each observation $x_i$ independent and\nidentically exponentially distributed for $i=1,2,\\dots,n$. That is,\n$x_i\\sim \\text{Exp}(\\lambda)$ where $\\lambda$ is the rate parameter. We\nwould like to find a posterior (or at least a function proportional to\nit) for $\\lambda$.\n\n### Part a (6 points)\n\nWrite down the likelihood function (or a function proportional to it) in\nthis situation. We would call this $p(x|\\lambda)$.\n\n$$\np(x|\\lambda)= \\prod_{i=1}^{n}\\lambda e^{- \\lambda x_i}\n$$\n\n### Part b (6 points)\n\nNow let $\\lambda$ have a normal prior with mean 0.1 and variance 1:\n$\\lambda\\sim N(1/10,\\ 1)$. Use this and the likelihood from part (a) to\nwrite down a function that is proportional to the posterior of $\\lambda$\ngiven $\\boldsymbol{x}$. We call this $p(\\lambda|\\boldsymbol{x})$.\n\n$$\np(\\lambda | x) = \\lambda^n  exp(- \\lambda \\sum_{i=1}^{n} x_i)exp(-\\frac{(\\lambda - 0.1)^2}{2})\n$$\n\n### Part c (3 points)\n\nWhich would be more appropriate here to obtain samples of $\\lambda$, the\nGibbs or Metropolis algorithm? Explain why. You may want to look on page\n171 of Notes 9 in the conjugate prior table.\n\nThe Metropolis algorithm only requires a function proportional to the\nposterior, which I have.\n\n# Problem 3 (30 points)\n\nSuppose we have the vector\n`x = c(1.83, 1.72, 2.13, 2.49, 0.90, 2.01, 1.51, 3.12, 1.29, 1.54, 2.94, 3.02, 0.93, 2.78)`\nthat we believe comes from a gamma distribution with shape of 10 and\nsome rate $\\beta$: $x_i\\sim\\text{Gam}(10,\\ \\beta)$. We will use sampling\nto obtain some information about $\\beta$. Let’s put a gamma prior on\n$\\beta$ with a shape of $\\alpha_0$ and a rate of 1:\n$\\beta\\sim\\text{Gam}(\\alpha_0,\\ 1)$.\n\n### Part a (5 points)\n\nUse the fact that this is a conjugate prior to write down what kind of\ndistribution the posterior of $\\beta$, which is\n$p(\\beta|\\boldsymbol{x})$, is.\n\n$$\n\\beta | x ~ Gamma(\\alpha_0+10n, 1 + \\sum_{i=1}^{n}x_i) \n$$\n\n### Part b (5 points)\n\nLet $\\alpha_0=1$. In an **R** code chunk, sample 10,000 $\\beta$ values\nfrom the distribution you wrote down in part (a) using the `rgamma()`\nfunction and report the 95% credible interval for $\\beta$ using the\n2.5th and 97.5th percentiles.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = c(1.83, 1.72, 2.13, 2.49, 0.90, 2.01, 1.51, 3.12, 1.29, 1.54, 2.94, 3.02, 0.93, 2.78)\n\nn = length(x)\nalpha0 = 1\n\nshape = alpha0 + 10 *n\nrate = 1 + sum(x)\n\nset.seed(7)\nbeta = rgamma(10000, shape = shape, rate=rate)\nquantile(beta, c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n4.068934 5.667622 \n```\n\n\n:::\n:::\n\n\n\n\n(4.07, 5.67)\n\n### Part c (3 points)\n\nRepeat part (b) with $\\alpha_0 = 10$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = c(1.83, 1.72, 2.13, 2.49, 0.90, 2.01, 1.51, 3.12, 1.29, 1.54, 2.94, 3.02, 0.93, 2.78)\n\nn = length(x)\nalpha0 = 10\n\nshape = alpha0 + 10 *n\nrate = 1 + sum(x)\n\nset.seed(7)\nbeta = rgamma(10000, shape = shape, rate=rate)\nquantile(beta, c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n4.352704 6.001669 \n```\n\n\n:::\n:::\n\n\n\n\n(4.35, 6.00)\n\n### Part d (3 points)\n\nRepeat part (b) with $\\alpha_0 = 100$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = c(1.83, 1.72, 2.13, 2.49, 0.90, 2.01, 1.51, 3.12, 1.29, 1.54, 2.94, 3.02, 0.93, 2.78)\n\nn = length(x)\nalpha0 = 100\n\nshape = alpha0 + 10 *n\nrate = 1 + sum(x)\n\nset.seed(7)\nbeta = rgamma(10000, shape = shape, rate=rate)\nquantile(beta, c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n7.218877 9.296324 \n```\n\n\n:::\n:::\n\n\n\n\n7.22, 9.30\n\n### Part e (4 points)\n\nComment on the effect the value of $\\alpha_0$ has on the credible\nintervals for $\\beta$ as revealed in parts (b), (c), and (d).\n\nThe credible intervals got bigger as the value of $\\alpha_0$ increased.\n\n### Part f (6 points)\n\nNow suppose we have twice as much data (given in the **R** code chunk\nbelow). Repeat parts (b), (c), and (d) using this `x` vector given below\ninstead of the other one and report the three 95% credible intervals.\nNote, this new vector x will change the shape and rate parameters used\nin the `rgamma()` functions.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(1.83, 1.72, 2.13, 2.49, 0.90, 2.01, 1.51, 3.12, 1.29, 1.54,\n       2.94, 3.02, 0.93, 2.78, 2.76, 1.70, 1.42, 2.16, 1.07, 2.21,\n       2.38, 2.27, 1.72, 1.44, 1.54, 1.72, 1.87, 1.39)\n```\n:::\n\n\n\n\n### Part g (4 points)\n\nIn this problem, the true $\\beta$ value is 5. Write a sentence or two\nabout the effect adding more data has to these credible intervals by\ncomparing the intervals from parts (b)-(d) to the intervals from part\n(f).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = length(x)\nalpha0 = 10\n\nshape = alpha0 + 10 *n\nrate = 1 + sum(x)\n\nset.seed(7)\nbeta = rgamma(10000, shape = shape, rate=rate)\nquantile(beta, c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n4.700751 5.915869 \n```\n\n\n:::\n:::\n\n\n\n\nThe credible intervals are smaller when adding more data.\n\n# Problem 4 (35 points)\n\nLet’s apply the Bayesian framework to a regression problem. In the\n`math3190package` library is the `treeseeds` dataset (it is also on\nGitHub) that contains information about species of tree, the count of\nseeds it produces, and the average weight of those seeds in mg.\n\n### Part a (3 points)\n\nUsing the `treeseeds` data, create new variables defined by taking the\nlog of the counts and weights. Fit an OLS regression model using logged\nweight to predict logged count.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(math3190package) |> suppressPackageStartupMessages()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code}\ntree <- treeseeds |>\n  mutate(lcount = log(count),\n         lweight = log(weight))\n\n# Fit model here\nmod = lm(lcount ~ lweight, data = tree)\n```\n:::\n\n\n\n\n### Part b (5 points)\n\nPlease read this carefully and try to understand what is being done\nhere. There is just one question at the end of this part for you. We\nwill walk through the mathematics and code of obtaining the posterior\nand samples together here since this problem will focus on looking at\ndiagnostics, but I want you to see the **Metropolis algorithm** in\naction! Make sure to read this in the html or pdf file where all\nequations are rendered nicely.\n\nAssuming the true errors are normal with mean 0 and variance $\\sigma^2$,\n$\\epsilon_i\\sim N(0,\\ \\sigma^2)$, it can be shown that each $y_i$ has\nthe distribution $$\np(y_i|x_i,\\beta_0,\\beta_1\\sigma^2) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}}\\exp\\left(\n-\\frac{1}{2\\sigma^2}(y_i-\\beta_0-\\beta_1x_i)^2\\right)\n$$\n\nSo, we can write the likelihood is $$\np(y_i|x_i,\\beta_0,\\beta_1\\sigma^2)\\propto\\exp\\left(\n-\\frac{1}{2\\sigma^2}(y_i-\\beta_0-\\beta_1x_i)^2\\right)\n$$ where $y_i$ is the log(count) for observation $i$ and $x_i$ is the\nlog(weight) for observation $i$. Note that here we think of\n$\\boldsymbol{y}$ as being random and $\\boldsymbol{x}$ as being fixed. We\ncould, in theory, think of the vector $\\boldsymbol{x}$ as also being\nrandom and put a prior on it. But we won’t do that here.\n\nNow, let’s just put uniform priors on $\\beta_0$ and $\\beta_1$ so the\npriors are proportional to 1. Also, let’s assume $\\sigma^2=1$. This\nseems reasonable since $s_e^2$, the MSE, is 0.877. Of course, we could\nput a prior on $\\sigma^2$ as well and sample it too, but we will focus\non only sampling $\\beta_0$ and $\\beta_1$.\n\nNow, with those uniform priors, and plugging in 1 for $\\sigma^2$, we\nhave that the joint posterior of $\\beta_0$ and $\\beta_1$ is: $$\np(\\beta_0,\\beta_1|\\boldsymbol{x},\\boldsymbol{y}) \\propto\\exp\\left(\n-\\frac{1}{2}\\sum_{i=1}^n(y_i-\\beta_0-\\beta_1x_i)^2\\right)=f(\\beta_0,\\beta_1|\\boldsymbol{x},\\boldsymbol{y}).\n$$\n\nThen, we can take the log to get $$\n\\ln(f(\\beta_0,\\beta_1|\\boldsymbol{x},\\boldsymbol{y}))=-\\frac{1}{2}\\sum_{i=1}^n(y_i-\\beta_0-\\beta_1x_i)^2.\n$$\n\nOur goal now is to obtain samples of $\\beta_0$ and $\\beta_1$. Let’s use\nthe Metropolis algorithm to do this. Using the log of the function\nproportional to the joint posterior of $\\beta_0$ and $\\beta_1$,\n$\\ln\\Big(f(\\beta_0,\\beta_1|\\boldsymbol{x},\\boldsymbol{y})\\Big)$, we'll\nwrite a Metropolis algorithm in **R**. For $\\beta_0$, we will use a\nnormal proposal distribution centered at the previous value,\n$\\beta_0^{(i)}$, with a standard deviation of 0.8 and for $\\beta_1$, and\nwe will use a normal proposal distribution centered at the previous\nvalue, $\\beta_1^{(i)}$, with a standard deviation of 0.1. The starting\nvalues don’t matter too much, but we'll use $\\beta_0^{(0)}=10$ and\n$\\beta_1^{(0)}=-0.5$.\n\nThis code will generate 10,000 samples and plot the chains for $\\beta_0$\nand $\\beta_1$. In addition, the 95% credible interval for $\\beta_0$ and\n$\\beta_1$ are given.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'patchwork' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(2026)\nnsamps <- 10000\nbeta0 <- rep(0, nsamps)\nbeta1 <- rep(0, nsamps)\nbeta0[1] <- 10\nbeta1[1] <- -0.5\nfor (i in 1:(nsamps - 1)) {\n  beta0_star <- rnorm(1, beta0[i], 0.8) # Proposed new value for intercept\n  beta1_star <- rnorm(1, beta1[i], 0.1) # Proposed new value for slope\n  # y is tree$lcount and x is tree$lweight\n  lf1 <- -1 / 2 * sum((tree$lcount - beta0_star - beta1_star * tree$lweight)^2)\n  lf2 <- -1 / 2 * sum((tree$lcount - beta0[i] - beta1[i] * tree$lweight)^2)\n  if (log(runif(1)) < lf1 - lf2) {\n    # Accept the proposed values as new sample values if the above \n    #   condition is satisfied\n    beta0[i + 1] <- beta0_star\n    beta1[i + 1] <- beta1_star\n  } else {\n    # Otherwise set the new sample values to be equal to the previous ones\n    beta0[i + 1] <- beta0[i]\n    beta1[i + 1] <- beta1[i]\n  }\n}\n\nmcmc_df <- data.frame(index = 1:nsamps, beta0 = beta0, beta1 = beta1)\nmcmc_plot1 <- \n  ggplot(mcmc_df, aes(x = index, y = beta0)) +\n  geom_line() +\n  theme_test() +\n  scale_x_continuous(breaks = seq(0, 10000, by = 2000)) +\n  scale_y_continuous(breaks = seq(8, 11, by = 0.5)) + \n  labs(x = \"Index\", y = expression(beta[0]))\n\nmcmc_plot2 <- \n  ggplot(mcmc_df, aes(x = index, y = beta1)) +\n  geom_line() +\n  theme_test() +\n  scale_x_continuous(breaks = seq(0, 10000, by = 2000)) +\n  scale_y_continuous(breaks = seq(-0.75, -0.25, by = 0.1)) + \n  labs(x = \"Index\", y = expression(beta[1]))\n\nmcmc_plot1 / mcmc_plot2\n```\n\n::: {.cell-output-display}\n![](Homework_8_files/figure-html/mcmc-1.png){width=768}\n:::\n\n```{.r .cell-code}\nquantile(beta0, c(.025, .975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     2.5%     97.5% \n 8.526416 10.210557 \n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(beta1, c(.025, .975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      2.5%      97.5% \n-0.6606829 -0.3681291 \n```\n\n\n:::\n:::\n\n\n\n\nThe plots of the chains are given in the output above.\n\nThe 95% credible interval for $\\beta_0$ is $(8.53, 10.21)$.\n\nThe 95% credible interval for $\\beta_1$ is $(-0.661, -0.368)$.\n\nYour intervals may differ a bit due to the random sampling.\n\nOkay, here is the question for you! Based on the plots of the chains\nabove, does it look like the Metropolis sampling worked fairly well?\nExplain.\n\n### Part c (3 points)\n\nInterpret both of the credible intervals from part (b).\n\nThere is a 95% chance that $\\beta_0$ lies between 8.53 and 10.21\n\nThere is a 95% chance that $\\beta_1$ lies between -0.661 and -0.368\n\n### Part d (5 points)\n\nFind and report the integrated autocorrelation time for the $\\beta_0$\nand $\\beta_1$ chains. Each chain will have their own $\\hat{\\tau}_{int}$\nvalue, so you should report two (although they will be similar).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 + 2 * sum(abs(acf(beta0, lag.max = 100, plot = F)$acf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25.73468\n```\n\n\n:::\n\n```{.r .cell-code}\n1 + 2 * sum(abs(acf(beta1, lag.max = 100, plot = F)$acf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 26.61679\n```\n\n\n:::\n:::\n\n\n\n\n$\\beta_0$: 25.73\n\n$\\beta_1$: 26.62\n\n### Part e (3 points)\n\nBased on the integrated autocorrelation time for the $\\beta_0$ and\n$\\beta_1$ chains, how many MCMC samples would you need to generate to\nget the equivalent of 10,000 independent samples?\n\n370 MCMC samples\n\n### Part f (3 points)\n\nLet’s compare these credible intervals to some other intervals. First,\nobtain the 95% $t$ confidence intervals for $\\beta_0$ and $\\beta_1$ just\nusing the `confint()` function on the model you fit in part (a) and\nreport them here.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept)  8.5410148 10.2170375\nlweight     -0.6665051 -0.3633051\n```\n\n\n:::\n:::\n\n\n\n\n$\\beta_0$: (8.54, 10.22)\n\n$\\beta_1$: (-0.67, -0.36)\n\n### Part g (8 points)\n\nNow let's obtain confidence intervals using bootstrapping the cases like\nwe did with in Notes 7 and HW 5. You can use the `bootstrapping()`\nfunction in the `math3190package` for this or do it yourself with a\nloop. Set a seed and then using at least 10,000 bootstrap samples,\nreport the 95% percentile confidence intervals for $\\beta_0$ and\n$\\beta_1$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(math3190package)\nset.seed(7)\n\nbootcases = function(resids, i){\n  lm(lcount ~ lweight, data = tree[i,])$coef\n}\nboot = bootstrapping(residuals(mod), bootcases, 5000)\nboot_ci(boot)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\nWarning in boot.ci(boot_out, conf, type, index = index, ...): bootstrap\nvariances needed for studentized intervals\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 5000 bootstrap replicates\n\nInfo for stat1\n# A tibble: 4 × 4\n  interval_type conf_level lower upper\n  <chr>              <dbl> <dbl> <dbl>\n1 normal              0.95  8.41  10.3\n2 basic               0.95  8.47  10.3\n3 percent             0.95  8.41  10.3\n4 bca                 0.95  8.13  10.1\n\nInfo for stat2\n# A tibble: 4 × 4\n  interval_type conf_level  lower  upper\n  <chr>              <dbl>  <dbl>  <dbl>\n1 normal              0.95 -0.670 -0.356\n2 basic               0.95 -0.679 -0.365\n3 percent             0.95 -0.665 -0.351\n4 bca                 0.95 -0.645 -0.324\n\nCalculations and Intervals on Original Scale\nSome BCa intervals may be unstable\n```\n\n\n:::\n:::\n\n\n\n\n$\\beta_0$: (8.13, 10.1)\n\n$\\beta_1$: (-0.645, -0.324)\n\n### Part i (5 points)\n\nWrite a couple sentences comparing all of the intervals in parts (b),\n(f), and (g).\n\nPart b and f have almost the same intervals. The bootstrapped confidence\nintervals are slightly smaller than the other two.\n",
    "supporting": [
      "Homework_8_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}