{
  "hash": "98ccc5c5acd9d5dca32757c2a0d6878c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"**MATH 3190 Homework 7**\"\nsubtitle: |\n  Due March 26, 2026\\\n  Focus: Notes 8\\\n  Total Points: 90 + 10 (Self-Critique Comment and Uploading to GitHub) = 100\nformat: \n  html:\n    embed-resources: true # Keep this so the html file is easily shareable.\nurlcolor: blue\nexecute: # Will set these as the default for all code chunks\n  eval: true\n  echo: true\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\nNote that your homework should be completed in Quarto. You can just add your answers and code to this document in the appropriate part. The file should be rendered as an html document or pdf document (html is quicker to render and you will need an installation of LaTeX to render as a pdf). You will \"turn in\" this homework by uploading the files, the .qmd and output file, to your GitHub `Math_3190_Assignment` repository in the `Homework/Homework_7` directory. Make sure all supporting files (if there are any) are in this directory as well. You should use `git` and `Unix` commands in a terminal for this (i.e. don't manually upload files to GitHub). In addition, you will submit just your html or pdf file on Canvas to unlock the solutions.\n\nDon't forget to also put a [self-critique comment]{.underline} on Canvas indicating what you did correctly and incorrectly and include any questions you may have about the assignment after submitting the assignment and thoroughly looking through the solutions.\n\n# Problem 1 (57 points)\n\nIn Homework 6, we briefly looked at a small sample from this data set. Now we have the full data set with 20,640 districts. For districts in California from 1990, we want to predict the median house value for the district based on the district location (longitude and latitude), the median house age in the block group, the total number of rooms in the homes, the total number of bedrooms, the population in the district, the number of households, and the median income (in \\$10,000). These data were obtained from [scikit-learn.org](https://scikit-learn.org/stable/datasets.html) and can be found in the Data folder of the Math3190_Sp26 GitHub repo with the name `cal_housing.data`.\n\n### Part a (5 points)\n\nRead in the data. The `read.csv()` function works for files that end in `.data` if they are comma separated like this file is. However, be aware that the housing data does not have column names, so make sure to put `header = FALSE`. Assign appropriate column names to the columns and then take logs (base e) of all variables except lat and long. Once this is done, split the data into training and testing sets with the testing containing 20% of the values. Set a seed when you do this.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(math3190package)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: tidyverse\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.1.0     \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\ndf = read.csv(\"cal_housing.data\", header=FALSE)\n\ndf = df |>\n  rename(long=V1,\n         lat = V2,\n         house_age = V3,\n         total_rooms = V4,\n         total_bedrooms = V5,\n         population = V6,\n         num_household = V7,\n         med_income = V8,\n         med_house_val = V9\n         ) |>\n  mutate(l_house_age = log(house_age),\n         l_total_rooms = log(total_rooms),\n         l_total_bedrooms = log(total_bedrooms),\n         l_population = log(population),\n         l_num_houshold = log(num_household),\n         l_med_income = log(med_income),\n         l_med_house_val = log(med_house_val)) |>\n  select(-house_age, -total_rooms,-total_bedrooms,-population,-num_household,-med_income,-med_house_val)\n  \n\n\n\n# split into train/test\ny = df$l_med_house_val\nx = df[, -9]\n\nlibrary(caret)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'caret' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: lattice\n\nAttaching package: 'caret'\n\nThe following object is masked from 'package:purrr':\n\n    lift\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(7)\ntest_index = createDataPartition(y, times=1, p= 0.2, list=FALSE)\n\ntest_set = df[test_index,]\ntrain_set = df[-test_index,]\n```\n:::\n\n\n\n\n### Part b (5 points)\n\nUse the following command to view pair-wise scatter plots for the data here. Change `housing_train` to whatever you called the training set and be sure to change the `eval` option for the code chunk to `true`. Note, that `lower` option changes the points to be plotted with periods instead of circles. This speeds up plotting time considerably and makes the plots more readable since there are many data points here.\n\nBased on these plots, does multicollinearity appear to be an issue here? Explain.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GGally)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'GGally' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code}\nggpairs(train_set, \n        lower = list(continuous = wrap(\"points\", shape = \".\"))\n)\n```\n\n::: {.cell-output-display}\n![](Homework_7_files/figure-html/part_1b-1.png){width=672}\n:::\n:::\n\n\n\n\nYes, V2 and V1 has a correlation coefficient of -0.923, V5 and V4 has a correlation coefficient of 0.93, V6 and V4 have a correlation coefficient of 0.859, V4 and V7 have a correlation coefficient of 0.919, V5 and V7 have a correlation coefficient of 0.981, V6 and V7 have a correlation coefficient of 0.908, V5 and V6 have a correlation coefficient of 0.88.\n\n### Part c (4 points)\n\nFit a OLS regression model predicting house prices from all other variables. Check its summary output and its VIF values. Comment on the VIFs.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_model = lm(l_med_house_val~., df)\n\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'car' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'carData' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'car'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:purrr':\n\n    some\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(ols_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            long              lat      l_house_age    l_total_rooms \n        9.434524         9.967464         1.212756        24.847062 \nl_total_bedrooms     l_population   l_num_houshold     l_med_income \n       39.186028         8.187444        33.147774         2.769504 \n```\n\n\n:::\n:::\n\n\n\n\nAll variables have a VIF value higher than 5 except for house age and median income. Total bedrooms has a VIF of 39.19 and number of households has a VIF of 33.15. There is an issue with multicollinearity.\n\n### Part d (3 points)\n\nFit a principal component model using the `pcr()` function in the `pls` package. Since the variables are on very different scales, use the `scale = TRUE` option in the function. Then find the VIF values for this model. The `vif()` function from the `car` library won't work here. Instead, you can take the diagonals of the inverse of the correlation matrix (like is shown in the regularization section of Notes 7) for the `scores` output. The code for this is `diag(solve(cor(pca_model$scores)))`. Of course, you need to change `pca_model` to what you called your model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pls)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'pls'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:caret':\n\n    R2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:stats':\n\n    loadings\n```\n\n\n:::\n\n```{.r .cell-code}\npca_model = pcr(l_med_house_val~., data = df, scale=TRUE)\ndiag(solve(cor(pca_model$scores)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nComp 1 Comp 2 Comp 3 Comp 4 Comp 5 Comp 6 Comp 7 Comp 8 \n     1      1      1      1      1      1      1      1 \n```\n\n\n:::\n:::\n\n\n\n\n### Part e (5 points)\n\nNow take the summary of your principal component model. With PCA, the common amount of variation we want to explain in the predictors is 90% or more. How many components are needed to achieve this? For that number of components, how much of the variation in log of home values is explained? How many components are needed to explain a \"good\" amount of the variation in the log of home values? Note: the upper bound on the amount of variation in the log of home values here with all 8 components will be equal to the $R^2$ value of the OLS model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pca_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: \tX dimension: 20640 8 \n\tY dimension: 20640 1\nFit method: svdpc\nNumber of components considered: 8\nTRAINING: % variance explained\n                 1 comps  2 comps  3 comps  4 comps  5 comps  6 comps  7 comps\nX                 48.818   72.671    86.44    96.98    98.61    99.48    99.81\nl_med_house_val    1.739    2.322    26.04    49.41    49.59    66.83    66.83\n                 8 comps\nX                 100.00\nl_med_house_val    67.18\n```\n\n\n:::\n:::\n\n\n\n\nWe need 4 components. It will explain 96.36% of the variation in X. 52.39% percent of variation in log of home values will be explained. We will need 8 components to explain a good amount in y, but even then, it will only explain 63.71% of the variation.\n\n### Part f (4 points)\n\nNow fit a partial least squares model using the `plsr()` function in the `pls` package with `scale = TRUE`. Then find the VIF values for this model like you did in part (d) and comment on them.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplsr_mod = plsr(l_med_house_val~., data =df, scale = TRUE)\ndiag(solve(cor(plsr_mod$scores)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nComp 1 Comp 2 Comp 3 Comp 4 Comp 5 Comp 6 Comp 7 Comp 8 \n     1      1      1      1      1      1      1      1 \n```\n\n\n:::\n:::\n\n\n\n\n### Part g (4 points)\n\nNow take the summary of your partial least squares model. Compare this output to the summary of the PCA model. Explain what the differences are.\n\nHow many components are needed to balance a good amount of variation explained in $X$ and in $y$ for the PLS model?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(plsr_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: \tX dimension: 20640 8 \n\tY dimension: 20640 1\nFit method: kernelpls\nNumber of components considered: 8\nTRAINING: % variance explained\n                 1 comps  2 comps  3 comps  4 comps  5 comps  6 comps  7 comps\nX                  25.86    61.15    78.01    91.32    97.86    99.42    99.66\nl_med_house_val    40.75    51.81    54.96    60.41    66.92    67.03    67.18\n                 8 comps\nX                 100.00\nl_med_house_val    67.18\n```\n\n\n:::\n:::\n\n\n\n\nThe PLS model explains less of X and more of y. We need 5 components to get 97% of variation explained in X and 66.92% of variation explained in y.\n\n### Part h (8 points)\n\nIn part (e), you said how many components were needed for the PCA to explain a good amount of the $Y$ variable. Using that number of components, use the PCA and PLS models to find the root MSE when predicting the testing set. Note: the root MSE (or residual standard error, also abbreviated RMSE) is found by taking the square root of the sum of squared residuals divided by the residual degrees of freedom, which is $n-p-1$, where $p$ is the number of predictors in the model. Also, be aware that when you use the `predict()` function on your model, it will give you predictions for each number of components. You can access the predictions for using 3 components, for example, by typing `predict(pca_model, test_set)[,,3]`.\n\nThen in part (g), you said how many components were needed for the PLS Using that number of components. Using this number of components, use the PCA and PLS models to find the root MSE predicting the testing set.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: 1h\n\n# pca\npca_pred = predict(pca_model, test_set)[,,4]\ny_test = test_set$l_med_house_val\nrmse_pca = sqrt(sum((y_test - pca_pred)^2) / (length(y_test) - 4 - 1))\nrmse_pca\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.40708\n```\n\n\n:::\n\n```{.r .cell-code}\n#pls\npls_pred = predict(plsr_mod, test_set)[,,5]\nrmse_pls = sqrt(sum((y_test - pls_pred)^2) / (length(y_test) - 5 - 1))\nrmse_pls\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3401034\n```\n\n\n:::\n:::\n\n\n\n\nCompare the results of the predictions in both cases.\n\nThe PCA model has an RMSE of 0.41 while the PLS model has an RMSE of 0.34. The PLSS model is more accurate.\n\n### Part i (12 points)\n\nUsing the number of components you said were needed for the PLS model in part (g), come up with reasonable surrogates for each of those components. Look at the projection output for this. When creating your surrogates, make sure to center and scale each variable. You can do this with the `scale()` function and putting your housing data frame or tibble in it.\n\nThen fit a OLS model using those surrogates in the training set. Check the VIF of this model to make sure each one is below 5. If they are not, your surrogates should be changed. You can use the `vif()` function in the `car` package here.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(plsr_mod$projection, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Comp 1 Comp 2 Comp 3 Comp 4 Comp 5 Comp 6 Comp 7 Comp 8\nlong             -0.031 -0.285 -0.746 -0.620 -1.235 -0.272  0.046  0.320\nlat              -0.260 -0.198 -0.250 -1.097 -1.046 -0.202  0.062  0.343\nl_house_age       0.065  0.360  0.460  0.170 -0.594 -0.060  0.021  0.007\nl_total_rooms     0.251 -0.248 -0.098 -0.363 -0.477 -0.579 -0.350 -0.624\nl_total_bedrooms  0.119 -0.321  0.319  0.445  0.577  0.120  0.853  0.156\nl_population      0.036 -0.494 -0.234 -0.534 -0.810  0.689  0.115 -0.127\nl_num_houshold    0.153 -0.286  0.318  0.411  0.485 -0.244 -0.622  0.567\nl_med_income      0.909  0.891  0.013 -0.123 -0.019  0.111  0.111  0.171\n```\n\n\n:::\n\n```{.r .cell-code}\nX = select(train_set,-l_med_house_val)\nXs = scale(as.matrix(X))\n\nsurr1 = (Xs[,4] + Xs[,5] +Xs[,7] + Xs[,8])/4 - Xs[,2]\nsurr2 = Xs[,8]\nsurr3 = Xs[,3]-Xs[,1]\n# surr3 = (Xs[,3] + Xs[,5] + Xs[,7])/3 - (Xs[,1] + Xs[,2] + Xs[,6])/3\nsurr4 = (Xs[,5] + Xs[,7])/2 - (Xs[,1]+Xs[,2]+Xs[,6])/4\nsurr5 = (Xs[,1] + Xs[,2] + Xs[,3] + Xs[,4] + Xs[,6])/5\n\nsurr_mod = lm(l_med_house_val ~ surr1 + surr2 + surr3 + surr4 + surr5, data = train_set)\nvif(surr_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   surr1    surr2    surr3    surr4    surr5 \n4.043179 1.238183 2.618209 3.338319 3.909306 \n```\n\n\n:::\n:::\n\n\n\n\n### Part j (7 points)\n\nNow using that model you fit in the previous part with the surrogates, find the root MSE for predicting the testing set using that model, and compare it to what you got in part (h). Describe some pros and cons of the surrogate model.\n\nHint: to predict using this model, you will have to create a `newdata` data frame (or tibble) and then redefine your surrogates in that data frame using the scaled testing data set. Make sure the variable names in the `newdata` data frame match the variables names used in the model you defined in part (i).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# rotation <- pca_model$rotation[, 1:5]\n# \n# test_scaled <- scale(test_set[,-9],\n#                      center = attr(pca_model$scale, \"scaled:center\"),\n#                      scale  = attr(pca_model$scale, \"scaled:scale\"))\n#   \n# Z_test <- test_scaled %*% rotation\n# \n# # Put into dataframe with correct names\n# newdata <- as.data.frame(Z_test)\n# colnames(newdata) <- paste0(\"Z\", 1:k_pcr)\n# \n# pred <- predict(surr_mod, newdata = newdata)\n# \n# y_test <- test_set$l_med_house_val\n# n <- length(y_test)\n# p <- k_pcr\n# \n# rmse_surrogate <- sqrt(sum((y_test - pred)^2) / (n - p - 1))\n# rmse_surrogate\n```\n:::\n\n\n\n\n# Problem 2 (33 points)\n\nIn base **R**, there is a dataset called `penguins`. Type `?penguins` to read a little about the data.\n\n### Part a (6 points)\n\nRemove the rows in the penguins dataset that have missing values. Then use the `ggpairs()` function from `GGally` to make pairwise scatterplots for the four quantitative variables and color the points based on the `species` variable. Note that the `ggpairs()` function has a `columns` argument where you can select the columns you want to plot and it has a `mapping` argument where you can put `aes(color = species, alpha = 0.5)` to color the points by species.\n\nInclude the plot here and then comment on which scatterplots seem to nicely separate the penguins by species and which tend to have worse separation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GGally)\nlibrary(palmerpenguins)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'palmerpenguins' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code}\ndf2 = penguins\ndf2 = drop_na(df2)\n\nggpairs(df2, columns = 3:6, mapping = aes(color=species, alpha = 0.5))\n```\n\n::: {.cell-output-display}\n![](Homework_7_files/figure-html/2a-1.png){width=672}\n:::\n:::\n\n\n\n\nThe best scatterplots that separate the species seems to be bill length and flipper length. The worst one is body mass and flipper length.\n\n![](images/clipboard-3654661957.png)\n\n### Part b (4 points)\n\nRun a scaled principal component analysis on the four quantitative variables using the `prcomp()` function. How much of the total variation in these variables is explained by the first two principal components? You can use the `summary()` function on your PCA to find this easily.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: 2b\n\nX = df2[3:6]\npca = prcomp(X, scale=T)\nsummary(pca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2     PC3     PC4\nStandard deviation     1.6569 0.8821 0.60716 0.32846\nProportion of Variance 0.6863 0.1945 0.09216 0.02697\nCumulative Proportion  0.6863 0.8809 0.97303 1.00000\n```\n\n\n:::\n:::\n\n\n\n\nThe first two principal components will explain 85.08% of total variation.\n\n### Part c (6 points)\n\nPlot the first two principal components with PC1 on the x-axis and PC2 on the y-axis. Color the points by species and comment on how well the first two principal components are separating by species.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_df <- data.frame(\n  PC1 = pca$x[, 1],\n  PC2 = pca$x[, 2],\n  species = df2$species\n)\n\nggplot(pca_df, aes(x=PC1, y=PC2, color=species))+\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](Homework_7_files/figure-html/2c-1.png){width=672}\n:::\n:::\n\n\n\n\nIt does not separate Adelie and Chinstrap penguins very well, but it separates Gentoo penguins from the others very well.\n\n### Part d (12 points)\n\nNow use the `umap()` function in the `umap` library to fit a UMAP to the **scaled** quantitative variables in the penguins dataset. You can use the `scale()` function to scale the variables. Make sure the UMAP gives two components and set a `random_state` in the function so your results are reproducible. Then plot the UMAP using the the `umap_plot()` function in `math3190package` and color the points by `species` using the `color_umap` argument. Experiment with at least three different number of neighbors (`n_neighbors`) and at least three different minimum distances (`min_dist`).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(math3190package)\nlibrary(umap)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'umap' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code}\numap = umap(df2[3:6], n_components=2, random_state = 7, n_neighbors=15, min_dist=0.5)  \numap_plot(umap, data = df2, color_umap=\"species\", size=2) +\n  scale_color_viridis_d()\n```\n\n::: {.cell-output-display}\n![](Homework_7_files/figure-html/2d-1.png){width=672}\n:::\n\n```{.r .cell-code}\numap = umap(df2[3:6], n_components=2, random_state = 7, n_neighbors=50, min_dist=0.9)  \numap_plot(umap, data = df2, color_umap=\"species\", size=2) +\n  scale_color_viridis_d()\n```\n\n::: {.cell-output-display}\n![](Homework_7_files/figure-html/2d-2.png){width=672}\n:::\n\n```{.r .cell-code}\numap = umap(df2[3:6], n_components=2, random_state = 7, n_neighbors=100, min_dist=0.8)  \numap_plot(umap, data = df2, color_umap=\"species\", size=2) +\n  scale_color_viridis_d()\n```\n\n::: {.cell-output-display}\n![](Homework_7_files/figure-html/2d-3.png){width=672}\n:::\n:::\n\n\n\n\n### Part e (5 points)\n\nComment on the UMAP plots you made in part (d). Include a comparison to the PCA plot regarding how well these species are separated.\n\nFeel free to repeat this problem using a variable other than species! Sometimes the UMAP outperforms PCA at separating classes, sometimes it does a little worse, and sometimes there are both quite bad.\n\nThey were both pretty bad, but I think PCA was slightly better. Both had problems with discerning Adelie and Chinstrap.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}